export type UrduLetterForm = {
  glyph: string;
  hint: string;
};

export type UrduLetter = {
  name: string;
  alternates: string[];
  standalone: UrduLetterForm;
  initial: UrduLetterForm;
  medial: UrduLetterForm;
  final: UrduLetterForm;
};

export const UrduLetters: UrduLetter[] = [
  {
    name: "alef",
    alternates: ["alif", "a"],
    standalone: { glyph: "ﺍ", hint: "Alef in isolation: a single upright vertical stroke." },
    initial:    { glyph: "ﺍ", hint: "Alef at word start looks identical to standalone — it never connects to the following letter." },
    medial:     { glyph: "ﺎ", hint: "Alef in medial position looks like final — it attaches to the preceding letter but not the following." },
    final:      { glyph: "ﺎ", hint: "Alef final: the upright stroke attaches to the preceding letter's connecting line on its right." },
  },
  {
    name: "alef-madda",
    alternates: ["alef maddah", "aa", "a"],
    standalone: { glyph: "ﺁ", hint: "Alef with a wavy madda mark above it, in isolation." },
    initial:    { glyph: "ﺁ", hint: "Alef madda at word start looks identical to standalone — it does not connect forward." },
    medial:     { glyph: "ﺂ", hint: "Alef madda in medial position looks like final — attaches to the preceding letter but not the following." },
    final:      { glyph: "ﺂ", hint: "Alef madda final: wavy mark above, stroke attached to the preceding letter on its right." },
  },
  {
    name: "be",
    alternates: ["ba", "b"],
    standalone: { glyph: "ﺏ", hint: "Be standalone: a shallow bowl open at the top with one dot below and a small hook on the right." },
    initial:    { glyph: "ﺑ", hint: "Be initial: a short tooth-like stroke open to the right for connecting forward, one dot below." },
    medial:     { glyph: "ﺒ", hint: "Be medial: a tiny connecting tooth between letters, one dot below." },
    final:      { glyph: "ﺐ", hint: "Be final: the bowl extends into a long sweeping leftward tail, one dot below." },
  },
  {
    name: "pe",
    alternates: ["pa", "p"],
    standalone: { glyph: "ﭖ", hint: "Pe standalone: identical shape to be but with three dots below instead of one." },
    initial:    { glyph: "ﭘ", hint: "Pe initial: short connecting stroke open to the right, three dots below." },
    medial:     { glyph: "ﭙ", hint: "Pe medial: tiny connecting tooth, three dots below distinguish it from be." },
    final:      { glyph: "ﭗ", hint: "Pe final: same long sweeping tail as be's final form, three dots below." },
  },
  {
    name: "te",
    alternates: ["ta", "t"],
    standalone: { glyph: "ﺕ", hint: "Te standalone: like be but with two dots above the bowl." },
    initial:    { glyph: "ﺗ", hint: "Te initial: short connecting stroke open to the right, two dots above." },
    medial:     { glyph: "ﺘ", hint: "Te medial: tiny connecting tooth, two dots above the stroke." },
    final:      { glyph: "ﺖ", hint: "Te final: long leftward sweeping tail, two dots above." },
  },
  {
    name: "tte",
    alternates: ["te", "ta", "t"],
    standalone: { glyph: "ﭦ", hint: "Tte (retroflex) standalone: like te but with a small subscript retroflex mark below the bowl." },
    initial:    { glyph: "ﭨ", hint: "Tte initial: connecting stroke with the retroflex subscript mark below." },
    medial:     { glyph: "ﭩ", hint: "Tte medial: tiny tooth with the distinctive retroflex mark below." },
    final:      { glyph: "ﭧ", hint: "Tte final: sweeping tail with the retroflex subscript mark below, distinguishing it from te." },
  },
  {
    name: "se",
    alternates: ["sa", "s", "th", "theh"],
    standalone: { glyph: "ﺙ", hint: "Se (ث) standalone: like be but with three dots arranged in a triangle above the bowl." },
    initial:    { glyph: "ﺛ", hint: "Se initial: connecting stroke with three dots above in a triangular arrangement." },
    medial:     { glyph: "ﺜ", hint: "Se medial: tiny tooth with three dots above." },
    final:      { glyph: "ﺚ", hint: "Se final: sweeping tail with three dots above arranged in a triangle." },
  },
  {
    name: "jeem",
    alternates: ["jim", "j"],
    standalone: { glyph: "ﺝ", hint: "Jeem standalone: a rounded head with a deep downward hook and a dot inside the curve." },
    initial:    { glyph: "ﺟ", hint: "Jeem initial: the rounded head connects to the right, hook and dot visible below." },
    medial:     { glyph: "ﺠ", hint: "Jeem medial: small connecting form with the curved hook and dot below." },
    final:      { glyph: "ﺞ", hint: "Jeem final: the full deep downward hook with a dot, attached to the preceding letter." },
  },
  {
    name: "che",
    alternates: ["chay", "ch", "c"],
    standalone: { glyph: "ﭺ", hint: "Che standalone: like jeem but with three dots below the curve instead of one." },
    initial:    { glyph: "ﭼ", hint: "Che initial: jeem's initial connecting head with three dots below." },
    medial:     { glyph: "ﭽ", hint: "Che medial: small hook form, three dots below." },
    final:      { glyph: "ﭻ", hint: "Che final: deep downward hook, three dots below distinguishing it from jeem." },
  },
  {
    name: "hah",
    alternates: ["ha", "h"],
    standalone: { glyph: "ﺡ", hint: "Hah standalone: like jeem but with no dot — a rounded head and deep downward hook, empty inside." },
    initial:    { glyph: "ﺣ", hint: "Hah initial: the rounded connecting head, no dot unlike jeem or che." },
    medial:     { glyph: "ﺤ", hint: "Hah medial: curved hook form with no dot — absence of dot distinguishes it from jeem and che." },
    final:      { glyph: "ﺢ", hint: "Hah final: deep hook, no dot, attached to the preceding letter." },
  },
  {
    name: "khe",
    alternates: ["khay", "kh", "x"],
    standalone: { glyph: "ﺥ", hint: "Khe standalone: like hah but with a single dot above the head." },
    initial:    { glyph: "ﺧ", hint: "Khe initial: hah's initial form with one dot above." },
    medial:     { glyph: "ﺨ", hint: "Khe medial: curved hook form with one dot above." },
    final:      { glyph: "ﺦ", hint: "Khe final: deep hook like hah's final, one dot above." },
  },
  {
    name: "dal",
    alternates: ["daal", "d"],
    standalone: { glyph: "ﺩ", hint: "Dal standalone: a small angular wedge shape, open on the right." },
    initial:    { glyph: "ﺩ", hint: "Dal at word start looks identical to standalone — it never connects to the following letter." },
    medial:     { glyph: "ﺪ", hint: "Dal in medial position looks like final — the wedge attaches to the preceding letter's line." },
    final:      { glyph: "ﺪ", hint: "Dal final: the angular wedge hangs from the preceding letter's connecting stroke." },
  },
  {
    name: "ddal",
    alternates: ["dal", "daal", "d"],
    standalone: { glyph: "ﮈ", hint: "Ddal (retroflex) standalone: like dal but with a small subscript retroflex mark below the wedge." },
    initial:    { glyph: "ﮈ", hint: "Ddal at word start looks identical to standalone — non-connector with retroflex mark below." },
    medial:     { glyph: "ﮉ", hint: "Ddal in medial position looks like final — wedge with retroflex mark attaches to preceding letter." },
    final:      { glyph: "ﮉ", hint: "Ddal final: dal's wedge form with the retroflex subscript mark below." },
  },
  {
    name: "zal",
    alternates: ["zaal", "z", "dh"],
    standalone: { glyph: "ﺫ", hint: "Zal standalone: like dal but with a single dot above the wedge." },
    initial:    { glyph: "ﺫ", hint: "Zal at word start looks identical to standalone — non-connector with dot above." },
    medial:     { glyph: "ﺬ", hint: "Zal in medial position looks like final — the dotted wedge attaches to the preceding letter." },
    final:      { glyph: "ﺬ", hint: "Zal final: dal's final wedge with one dot above, hanging from the preceding letter." },
  },
  {
    name: "re",
    alternates: ["ra", "r"],
    standalone: { glyph: "ﺭ", hint: "Re standalone: a simple rightward-curving hook that dips below the baseline." },
    initial:    { glyph: "ﺭ", hint: "Re at word start looks identical to standalone — it never connects to the following letter." },
    medial:     { glyph: "ﺮ", hint: "Re in medial position looks like final — the hook hangs from the preceding letter's connecting stroke." },
    final:      { glyph: "ﺮ", hint: "Re final: the curved hook hangs down from the preceding letter's connecting stroke." },
  },
  {
    name: "rre",
    alternates: ["re", "ra", "r"],
    standalone: { glyph: "ﮌ", hint: "Rre (retroflex) standalone: like re but with a small subscript retroflex mark on the hook." },
    initial:    { glyph: "ﮌ", hint: "Rre at word start looks identical to standalone — non-connector with retroflex mark." },
    medial:     { glyph: "ﮍ", hint: "Rre in medial position looks like final — hook with retroflex mark attaches to preceding letter." },
    final:      { glyph: "ﮍ", hint: "Rre final: re's hooked final form with the distinctive retroflex subscript mark." },
  },
  {
    name: "zain",
    alternates: ["ze", "za", "z"],
    standalone: { glyph: "ﺯ", hint: "Zain standalone: like re but the curve extends slightly further left below the baseline." },
    initial:    { glyph: "ﺯ", hint: "Zain at word start looks identical to standalone — non-connector, similar to re." },
    medial:     { glyph: "ﺰ", hint: "Zain in medial position looks like final — the extended hook attaches to the preceding letter." },
    final:      { glyph: "ﺰ", hint: "Zain final: the slightly extended downward hook hangs from the preceding letter." },
  },
  {
    name: "zhe",
    alternates: ["zhay", "zh"],
    standalone: { glyph: "ﮊ", hint: "Zhe standalone: like zain but with three dots above the hook." },
    initial:    { glyph: "ﮊ", hint: "Zhe at word start looks identical to standalone — non-connector with three dots above." },
    medial:     { glyph: "ﮋ", hint: "Zhe in medial position looks like final — hook with three dots above attaches to preceding letter." },
    final:      { glyph: "ﮋ", hint: "Zhe final: zain's final hook with three dots above." },
  },
  {
    name: "seen",
    alternates: ["sin", "s"],
    standalone: { glyph: "ﺱ", hint: "Seen standalone: three small teeth followed by a long descending tail curving left." },
    initial:    { glyph: "ﺳ", hint: "Seen initial: the three teeth extend to the right for connecting, tail not yet formed." },
    medial:     { glyph: "ﺴ", hint: "Seen medial: three small teeth connecting on both sides, compressed in the middle of a word." },
    final:      { glyph: "ﺲ", hint: "Seen final: three teeth with the long descending tail, attached to the preceding letter." },
  },
  {
    name: "sheen",
    alternates: ["shin", "sh"],
    standalone: { glyph: "ﺵ", hint: "Sheen standalone: like seen but with three dots above the teeth." },
    initial:    { glyph: "ﺷ", hint: "Sheen initial: seen's initial teeth with three dots above." },
    medial:     { glyph: "ﺸ", hint: "Sheen medial: three teeth with three dots above, connecting on both sides." },
    final:      { glyph: "ﺶ", hint: "Sheen final: seen's final tail form with three dots above." },
  },
  {
    name: "sad",
    alternates: ["suad", "swad", "s"],
    standalone: { glyph: "ﺹ", hint: "Sad standalone: a closed rounded loop open toward the left with a tail." },
    initial:    { glyph: "ﺻ", hint: "Sad initial: the closed loop extends rightward to connect, tail not yet formed." },
    medial:     { glyph: "ﺼ", hint: "Sad medial: the closed loop sits on the connecting baseline between other letters." },
    final:      { glyph: "ﺺ", hint: "Sad final: the rounded loop with a tail, attached to the preceding letter." },
  },
  {
    name: "dad",
    alternates: ["duad", "dwad", "d", "z"],
    standalone: { glyph: "ﺽ", hint: "Dad standalone: like sad but with a single dot above the closed loop." },
    initial:    { glyph: "ﺿ", hint: "Dad initial: sad's initial connecting loop with one dot above." },
    medial:     { glyph: "ﻀ", hint: "Dad medial: the loop on the baseline with one dot above." },
    final:      { glyph: "ﺾ", hint: "Dad final: sad's final loop and tail with one dot above." },
  },
  {
    name: "tah",
    alternates: ["toe", "t"],
    standalone: { glyph: "ﻁ", hint: "Tah standalone: a large open loop with a vertical stroke rising from its right side." },
    initial:    { glyph: "ﻃ", hint: "Tah initial: the open loop extends rightward to connect, vertical stroke prominent." },
    medial:     { glyph: "ﻄ", hint: "Tah medial: the open loop and vertical stroke sit on the connecting baseline." },
    final:      { glyph: "ﻂ", hint: "Tah final: the full loop and vertical stroke, attached to the preceding letter." },
  },
  {
    name: "zah",
    alternates: ["zoe", "z"],
    standalone: { glyph: "ﻅ", hint: "Zah standalone: like tah but with a single dot above the vertical stroke." },
    initial:    { glyph: "ﻇ", hint: "Zah initial: tah's initial form with one dot above the vertical stroke." },
    medial:     { glyph: "ﻈ", hint: "Zah medial: tah's medial form with one dot above." },
    final:      { glyph: "ﻆ", hint: "Zah final: tah's final form with one dot above the stroke." },
  },
  {
    name: "ain",
    alternates: ["ayn", "a"],
    standalone: { glyph: "ﻉ", hint: "Ain standalone: an open angular form like a backwards 'c' with a tail curling below." },
    initial:    { glyph: "ﻋ", hint: "Ain initial: opens wide to the right to connect, like a cupped hand." },
    medial:     { glyph: "ﻌ", hint: "Ain medial: a compressed angular form on the baseline, connecting on both sides." },
    final:      { glyph: "ﻊ", hint: "Ain final: the open angular form with a downward tail, attached to the preceding letter." },
  },
  {
    name: "ghain",
    alternates: ["gain", "gh", "g"],
    standalone: { glyph: "ﻍ", hint: "Ghain standalone: like ain but with a single dot above the angular form." },
    initial:    { glyph: "ﻏ", hint: "Ghain initial: ain's initial open form with one dot above." },
    medial:     { glyph: "ﻐ", hint: "Ghain medial: ain's medial compressed form with one dot above." },
    final:      { glyph: "ﻎ", hint: "Ghain final: ain's final angular tail form with one dot above." },
  },
  {
    name: "fa",
    alternates: ["fe", "fay", "f"],
    standalone: { glyph: "ﻑ", hint: "Fa standalone: a rounded loop on the left with a small dot above and a tail curling right." },
    initial:    { glyph: "ﻓ", hint: "Fa initial: the round head extends to the right to connect, dot above." },
    medial:     { glyph: "ﻔ", hint: "Fa medial: the round head sits on the baseline connecting on both sides, dot above." },
    final:      { glyph: "ﻒ", hint: "Fa final: the round loop with dot above, attached to the preceding letter." },
  },
  {
    name: "qaf",
    alternates: ["qaaf", "q"],
    standalone: { glyph: "ﻕ", hint: "Qaf standalone: a deep rounded bowl open at the top with two dots above." },
    initial:    { glyph: "ﻗ", hint: "Qaf initial: the bowl connects to the right, two dots above." },
    medial:     { glyph: "ﻘ", hint: "Qaf medial: small connecting form with two dots above." },
    final:      { glyph: "ﻖ", hint: "Qaf final: the deep bowl with two dots above, attached to the preceding letter." },
  },
  {
    name: "kaf",
    alternates: ["kaaf", "k"],
    standalone: { glyph: "ﮎ", hint: "Kaf (keheh) standalone: a diagonal mark above a rounded bowl-like body." },
    initial:    { glyph: "ﮐ", hint: "Kaf initial: the diagonal mark is visible as the body opens rightward to connect." },
    medial:     { glyph: "ﮑ", hint: "Kaf medial: flat connecting stroke with the characteristic diagonal mark above." },
    final:      { glyph: "ﮏ", hint: "Kaf final: the diagonal mark sits over a closed body with a left-curling tail." },
  },
  {
    name: "gaf",
    alternates: ["gaaf", "g"],
    standalone: { glyph: "ﮒ", hint: "Gaf standalone: like kaf but with two diagonal marks above the body instead of one." },
    initial:    { glyph: "ﮔ", hint: "Gaf initial: kaf's initial connecting form with two diagonal marks above." },
    medial:     { glyph: "ﮕ", hint: "Gaf medial: flat connecting stroke with two diagonal marks above." },
    final:      { glyph: "ﮓ", hint: "Gaf final: kaf's final bowl and tail form with two diagonal marks above." },
  },
  {
    name: "lam",
    alternates: ["laam", "l"],
    standalone: { glyph: "ﻝ", hint: "Lam standalone: a tall stroke hooking upward at the top, with a long descending tail curving left." },
    initial:    { glyph: "ﻟ", hint: "Lam initial: rises tall and the baseline extends rightward to connect forward." },
    medial:     { glyph: "ﻠ", hint: "Lam medial: a vertical rise from the connecting baseline on both sides." },
    final:      { glyph: "ﻞ", hint: "Lam final: tall hook at top, connected from the right, tail curling down-left." },
  },
  {
    name: "meem",
    alternates: ["mim", "m"],
    standalone: { glyph: "ﻡ", hint: "Meem standalone: a closed round knob at the top with a small tail curling down and to the left." },
    initial:    { glyph: "ﻣ", hint: "Meem initial: the round head connects rightward, tail tucked inward." },
    medial:     { glyph: "ﻤ", hint: "Meem medial: a small round head sitting atop the connecting baseline." },
    final:      { glyph: "ﻢ", hint: "Meem final: the round head at the end, tail sweeping down-left." },
  },
  {
    name: "noon",
    alternates: ["nun", "n"],
    standalone: { glyph: "ﻥ", hint: "Noon standalone: a deep rounded bowl with one dot placed above, near the center." },
    initial:    { glyph: "ﻧ", hint: "Noon initial: resembles be's initial but the single dot sits above the stroke." },
    medial:     { glyph: "ﻨ", hint: "Noon medial: tiny connecting tooth with the dot above distinguishing it from be." },
    final:      { glyph: "ﻦ", hint: "Noon final: a broad sweeping curve to the left, one dot above." },
  },
  {
    name: "noon-ghunna",
    alternates: ["nun", "n", "ng"],
    standalone: { glyph: "ﮞ", hint: "Noon ghunna standalone: like noon but without the dot — a plain rounded bowl indicating the nasal sound." },
    initial:    { glyph: "ﮞ", hint: "Noon ghunna at word start looks identical to standalone — it does not connect to the following letter." },
    medial:     { glyph: "ﮟ", hint: "Noon ghunna in medial position looks like final — the dotless bowl attaches to the preceding letter." },
    final:      { glyph: "ﮟ", hint: "Noon ghunna final: a dotless noon bowl attached to the preceding letter, indicating the nasal sound." },
  },
  {
    name: "wao",
    alternates: ["waw", "vao", "w", "v", "u", "o"],
    standalone: { glyph: "ﻭ", hint: "Wao standalone: a closed teardrop loop with a tail curling down and to the left." },
    initial:    { glyph: "ﻭ", hint: "Wao at word start looks identical to standalone — it never connects to the following letter." },
    medial:     { glyph: "ﻮ", hint: "Wao in medial position looks like final — the teardrop hangs from the preceding letter's connecting stroke." },
    final:      { glyph: "ﻮ", hint: "Wao final: the teardrop loop hangs from the preceding letter's connecting stroke, tail below." },
  },
  {
    name: "he",
    alternates: ["hay", "h"],
    standalone: { glyph: "ﮪ", hint: "He (gol he) standalone: a rounded closed loop with a connecting entry from the right." },
    initial:    { glyph: "ﮬ", hint: "He initial: opens to the right to connect forward, the loop is visible." },
    medial:     { glyph: "ﮭ", hint: "He medial: a small figure-eight or knot shape connecting on both sides." },
    final:      { glyph: "ﮫ", hint: "He final: a rounded closed loop attached to the preceding letter." },
  },
  {
    name: "ye",
    alternates: ["yay", "y"],
    standalone: { glyph: "ﯼ", hint: "Ye (choti ye) standalone: two dots below a shallow curved form, like an upturned bowl." },
    initial:    { glyph: "ﯾ", hint: "Ye initial: a short tooth-like connecting stroke, two dots below." },
    medial:     { glyph: "ﯿ", hint: "Ye medial: tiny connecting tooth with two dots below." },
    final:      { glyph: "ﯽ", hint: "Ye final: a long sweeping tail to the left, two dots below." },
  },
  {
    name: "bari-ye",
    alternates: ["ye", "y"],
    standalone: { glyph: "ﮮ", hint: "Bari ye standalone: a long downward-swooping hook, broader than re, with no dots." },
    initial:    { glyph: "ﮮ", hint: "Bari ye at word start looks identical to standalone — it does not connect to the following letter." },
    medial:     { glyph: "ﮯ", hint: "Bari ye in medial position looks like final — the swooping hook attaches to the preceding letter." },
    final:      { glyph: "ﮯ", hint: "Bari ye final: the long sweeping downward hook attaches to the preceding letter, commonly seen at word ends." },
  },
];
