export type SentenceWord = {
  urdu: string;
  roman_primary: string;
  roman_accepted_variants: string[];
  english_meaning: string;
  components?: { urdu: string; name: string; roman: string; role: string }[];
};

export type UrduSentence = {
  id: string;
  urdu: string;
  roman_primary: string;
  roman_accepted_variants: string[];
  words: SentenceWord[];
  difficulty: "beginner" | "easy" | "medium";
};

export const UrduSentenceBank: UrduSentence[] = [
  {
    id: "s001",
    urdu: "آج موسم اچھا ہے",
    roman_primary: "aaj mausam achha hai",
    roman_accepted_variants: [
      "aaj mausam acha hai",
      "aj mausam achha hai",
      "aj mosam acha hai",
      "aaj mosam achha hai",
    ],
    words: [
      {
        urdu: "آج",
        roman_primary: "aaj",
        roman_accepted_variants: ["aj", "aaj"],
        english_meaning: "today",
        components: [
          { urdu: "آ", name: "alef-madda", roman: "alif madda", role: "vowel seat" },
          { urdu: "ج", name: "jeem", roman: "jeem", role: "consonant" },
        ],
      },
      {
        urdu: "موسم",
        roman_primary: "mausam",
        roman_accepted_variants: ["mosam", "mausam", "mousam"],
        english_meaning: "weather/season",
        components: [
          { urdu: "م", name: "meem", roman: "meem", role: "consonant" },
          { urdu: "و", name: "wao", roman: "wao", role: "vowel" },
          { urdu: "س", name: "seen", roman: "seen", role: "consonant" },
          { urdu: "م", name: "meem", roman: "meem", role: "consonant" },
        ],
      },
      {
        urdu: "اچھا",
        roman_primary: "achha",
        roman_accepted_variants: ["acha", "achha", "accha"],
        english_meaning: "good",
        components: [
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel seat" },
          { urdu: "چ", name: "che", roman: "che", role: "consonant" },
          { urdu: "ھ", name: "he", roman: "he", role: "aspirator" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
        components: [
          { urdu: "ہ", name: "he", roman: "he", role: "consonant" },
          { urdu: "ے", name: "bari-ye", roman: "bari ye", role: "vowel" },
        ],
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s002",
    urdu: "میرا نام علی ہے",
    roman_primary: "mera naam ali hai",
    roman_accepted_variants: [
      "mera nam ali hai",
      "mera naam alee hai",
      "mera nam alee hai",
    ],
    words: [
      {
        urdu: "میرا",
        roman_primary: "mera",
        roman_accepted_variants: ["mera", "maira", "myra"],
        english_meaning: "my",
        components: [
          { urdu: "م", name: "meem", roman: "meem", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "نام",
        roman_primary: "naam",
        roman_accepted_variants: ["naam", "nam"],
        english_meaning: "name",
        components: [
          { urdu: "ن", name: "noon", roman: "noon", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
          { urdu: "م", name: "meem", roman: "meem", role: "consonant" },
        ],
      },
      {
        urdu: "علی",
        roman_primary: "ali",
        roman_accepted_variants: ["ali", "alee"],
        english_meaning: "Ali (name)",
        components: [
          { urdu: "ع", name: "ain", roman: "ain", role: "consonant" },
          { urdu: "ل", name: "lam", roman: "lam", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s003",
    urdu: "یہ کتاب اچھی ہے",
    roman_primary: "ye kitab achhi hai",
    roman_accepted_variants: [
      "ye kitab achi hai",
      "ye kitaab achhi hai",
      "ye kitaab achi hai",
      "yi kitab achhi hai",
    ],
    words: [
      {
        urdu: "یہ",
        roman_primary: "ye",
        roman_accepted_variants: ["ye", "yi", "yah", "yeh"],
        english_meaning: "this",
        components: [
          { urdu: "ی", name: "ye", roman: "ye", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "vowel" },
        ],
      },
      {
        urdu: "کتاب",
        roman_primary: "kitab",
        roman_accepted_variants: ["kitab", "kitaab", "ketaab", "ketab"],
        english_meaning: "book",
        components: [
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ت", name: "te", roman: "te", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
          { urdu: "ب", name: "be", roman: "be", role: "consonant" },
        ],
      },
      {
        urdu: "اچھی",
        roman_primary: "achhi",
        roman_accepted_variants: ["achi", "achhi", "acchi"],
        english_meaning: "good (feminine)",
        components: [
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel seat" },
          { urdu: "چ", name: "che", roman: "che", role: "consonant" },
          { urdu: "ھ", name: "he", roman: "he", role: "aspirator" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s004",
    urdu: "میں گھر جا رہا ہوں",
    roman_primary: "main ghar ja raha hoon",
    roman_accepted_variants: [
      "main ghar ja raha hun",
      "mein ghar ja raha hoon",
      "main ghar ja raha hu",
      "main ghar jaa raha hoon",
    ],
    words: [
      {
        urdu: "میں",
        roman_primary: "main",
        roman_accepted_variants: ["main", "mein", "mai", "me"],
        english_meaning: "I",
        components: [
          { urdu: "م", name: "meem", roman: "meem", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
          { urdu: "ں", name: "noon-ghunna", roman: "noon ghunna", role: "nasal" },
        ],
      },
      {
        urdu: "گھر",
        roman_primary: "ghar",
        roman_accepted_variants: ["ghar", "gahr", "gher"],
        english_meaning: "home",
        components: [
          { urdu: "گ", name: "gaf", roman: "gaf", role: "consonant" },
          { urdu: "ھ", name: "he", roman: "he", role: "aspirator" },
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
        ],
      },
      {
        urdu: "جا",
        roman_primary: "ja",
        roman_accepted_variants: ["ja", "jaa", "jha"],
        english_meaning: "go",
        components: [
          { urdu: "ج", name: "jeem", roman: "jeem", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "رہا",
        roman_primary: "raha",
        roman_accepted_variants: ["raha", "reha", "rahaa"],
        english_meaning: "staying/remaining (masculine)",
        components: [
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "ہوں",
        roman_primary: "hoon",
        roman_accepted_variants: ["hoon", "hun", "hu", "ho"],
        english_meaning: "am",
        components: [
          { urdu: "ہ", name: "he", roman: "he", role: "consonant" },
          { urdu: "و", name: "wao", roman: "wao", role: "vowel" },
          { urdu: "ں", name: "noon-ghunna", roman: "noon ghunna", role: "nasal" },
        ],
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s005",
    urdu: "آپ کیسے ہیں",
    roman_primary: "aap kaise hain",
    roman_accepted_variants: [
      "aap kaise hain",
      "ap kaise hain",
      "aap kese hain",
      "ap kese hain",
      "aap kaise hai",
    ],
    words: [
      {
        urdu: "آپ",
        roman_primary: "aap",
        roman_accepted_variants: ["aap", "ap"],
        english_meaning: "you (formal)",
        components: [
          { urdu: "آ", name: "alef-madda", roman: "alif madda", role: "vowel seat" },
          { urdu: "پ", name: "pe", roman: "pe", role: "consonant" },
        ],
      },
      {
        urdu: "کیسے",
        roman_primary: "kaise",
        roman_accepted_variants: ["kaise", "kese", "kaisay", "kesay"],
        english_meaning: "how",
        components: [
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
          { urdu: "س", name: "seen", roman: "seen", role: "consonant" },
          { urdu: "ے", name: "bari-ye", roman: "bari ye", role: "vowel" },
        ],
      },
      {
        urdu: "ہیں",
        roman_primary: "hain",
        roman_accepted_variants: ["hain", "hyn", "hai"],
        english_meaning: "are (plural)",
        components: [
          { urdu: "ہ", name: "he", roman: "he", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
          { urdu: "ں", name: "noon-ghunna", roman: "noon ghunna", role: "nasal" },
        ],
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s006",
    urdu: "وہ گھر جا رہا ہے",
    roman_primary: "woh ghar ja raha hai",
    roman_accepted_variants: [
      "woh ghar ja raha hai",
      "wo ghar ja raha hai",
      "vo ghar ja raha hai",
      "woh ghar jaa raha hai",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/she/that",
        components: [
          { urdu: "و", name: "wao", roman: "wao", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "vowel" },
        ],
      },
      {
        urdu: "گھر",
        roman_primary: "ghar",
        roman_accepted_variants: ["ghar", "gahr", "gher"],
        english_meaning: "home",
      },
      {
        urdu: "جا",
        roman_primary: "ja",
        roman_accepted_variants: ["ja", "jaa", "jha"],
        english_meaning: "go",
      },
      {
        urdu: "رہا",
        roman_primary: "raha",
        roman_accepted_variants: ["raha", "reha", "rahaa"],
        english_meaning: "staying (masculine)",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s007",
    urdu: "یہ پانی ہے",
    roman_primary: "ye paani hai",
    roman_accepted_variants: [
      "ye paani hai",
      "ye pani hai",
      "yi paani hai",
      "ye pani hy",
    ],
    words: [
      {
        urdu: "یہ",
        roman_primary: "ye",
        roman_accepted_variants: ["ye", "yi", "yah", "yeh"],
        english_meaning: "this",
      },
      {
        urdu: "پانی",
        roman_primary: "paani",
        roman_accepted_variants: ["paani", "pani"],
        english_meaning: "water",
        components: [
          { urdu: "پ", name: "pe", roman: "pe", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
          { urdu: "ن", name: "noon", roman: "noon", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s008",
    urdu: "میرا دوست اچھا ہے",
    roman_primary: "mera dost achha hai",
    roman_accepted_variants: [
      "mera dost acha hai",
      "mera dost achha hai",
      "mera dost accha hai",
    ],
    words: [
      {
        urdu: "میرا",
        roman_primary: "mera",
        roman_accepted_variants: ["mera", "maira", "myra"],
        english_meaning: "my",
      },
      {
        urdu: "دوست",
        roman_primary: "dost",
        roman_accepted_variants: ["dost", "dost"],
        english_meaning: "friend",
        components: [
          { urdu: "د", name: "dal", roman: "dal", role: "consonant" },
          { urdu: "و", name: "wao", roman: "wao", role: "vowel" },
          { urdu: "س", name: "seen", roman: "seen", role: "consonant" },
          { urdu: "ت", name: "te", roman: "te", role: "consonant" },
        ],
      },
      {
        urdu: "اچھا",
        roman_primary: "achha",
        roman_accepted_variants: ["acha", "achha", "accha"],
        english_meaning: "good",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s009",
    urdu: "وہ کہاں ہے",
    roman_primary: "woh kahan hai",
    roman_accepted_variants: [
      "woh kahan hai",
      "wo kahan hai",
      "vo kahan hai",
      "woh kahan hy",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/she/that",
      },
      {
        urdu: "کہاں",
        roman_primary: "kahan",
        roman_accepted_variants: ["kahan", "kahan"],
        english_meaning: "where",
        components: [
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
          { urdu: "ں", name: "noon-ghunna", roman: "noon ghunna", role: "nasal" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s010",
    urdu: "یہ میری کتاب ہے",
    roman_primary: "ye meri kitab hai",
    roman_accepted_variants: [
      "ye meri kitab hai",
      "ye meri kitaab hai",
      "yi meri kitab hai",
    ],
    words: [
      {
        urdu: "یہ",
        roman_primary: "ye",
        roman_accepted_variants: ["ye", "yi", "yah", "yeh"],
        english_meaning: "this",
      },
      {
        urdu: "میری",
        roman_primary: "meri",
        roman_accepted_variants: ["meri", "mairi", "myri"],
        english_meaning: "my (feminine)",
        components: [
          { urdu: "م", name: "meem", roman: "meem", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
        ],
      },
      {
        urdu: "کتاب",
        roman_primary: "kitab",
        roman_accepted_variants: ["kitab", "kitaab", "ketaab", "ketab"],
        english_meaning: "book",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s011",
    urdu: "بچہ کھیل رہا ہے",
    roman_primary: "bachcha khel raha hai",
    roman_accepted_variants: [
      "bachcha khel raha hai",
      "bacha khel raha hai",
      "baccha khel raha hai",
      "bachcha khel raha hy",
    ],
    words: [
      {
        urdu: "بچہ",
        roman_primary: "bachcha",
        roman_accepted_variants: ["bachcha", "bacha", "baccha"],
        english_meaning: "child",
        components: [
          { urdu: "ب", name: "be", roman: "be", role: "consonant" },
          { urdu: "چ", name: "che", roman: "che", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "vowel" },
        ],
      },
      {
        urdu: "کھیل",
        roman_primary: "khel",
        roman_accepted_variants: ["khel", "khel"],
        english_meaning: "play",
        components: [
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ھ", name: "he", roman: "he", role: "aspirator" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
          { urdu: "ل", name: "lam", roman: "lam", role: "consonant" },
        ],
      },
      {
        urdu: "رہا",
        roman_primary: "raha",
        roman_accepted_variants: ["raha", "reha", "rahaa"],
        english_meaning: "staying (masculine)",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s012",
    urdu: "آپ کا نام کیا ہے",
    roman_primary: "aap ka naam kya hai",
    roman_accepted_variants: [
      "aap ka naam kya hai",
      "ap ka nam kya hai",
      "aap ka nam kia hai",
      "ap ka nam kya hy",
    ],
    words: [
      {
        urdu: "آپ",
        roman_primary: "aap",
        roman_accepted_variants: ["aap", "ap"],
        english_meaning: "you (formal)",
      },
      {
        urdu: "کا",
        roman_primary: "ka",
        roman_accepted_variants: ["ka", "kaa"],
        english_meaning: "of (masculine)",
        components: [
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "نام",
        roman_primary: "naam",
        roman_accepted_variants: ["naam", "nam"],
        english_meaning: "name",
      },
      {
        urdu: "کیا",
        roman_primary: "kya",
        roman_accepted_variants: ["kya", "kia"],
        english_meaning: "what",
        components: [
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s013",
    urdu: "وہ اچھی لڑکی ہے",
    roman_primary: "woh achhi ladki hai",
    roman_accepted_variants: [
      "woh achhi ladki hai",
      "wo achi ladki hai",
      "vo achhi ladki hai",
      "woh achi ladki hy",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "she/that",
      },
      {
        urdu: "اچھی",
        roman_primary: "achhi",
        roman_accepted_variants: ["achi", "achhi", "acchi"],
        english_meaning: "good (feminine)",
      },
      {
        urdu: "لڑکی",
        roman_primary: "ladki",
        roman_accepted_variants: ["ladki", "larki"],
        english_meaning: "girl",
        components: [
          { urdu: "ل", name: "lam", roman: "lam", role: "consonant" },
          { urdu: "ڑ", name: "rre", roman: "rre", role: "consonant" },
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s014",
    urdu: "وہ اچھا لڑکا ہے",
    roman_primary: "woh achha ladka hai",
    roman_accepted_variants: [
      "woh achha ladka hai",
      "wo acha ladka hai",
      "vo achha ladka hai",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/that",
      },
      {
        urdu: "اچھا",
        roman_primary: "achha",
        roman_accepted_variants: ["acha", "achha", "accha"],
        english_meaning: "good",
      },
      {
        urdu: "لڑکا",
        roman_primary: "ladka",
        roman_accepted_variants: ["ladka", "larka"],
        english_meaning: "boy",
        components: [
          { urdu: "ل", name: "lam", roman: "lam", role: "consonant" },
          { urdu: "ڑ", name: "rre", roman: "rre", role: "consonant" },
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s015",
    urdu: "یہ میرا گھر ہے",
    roman_primary: "ye mera ghar hai",
    roman_accepted_variants: [
      "ye mera ghar hai",
      "yi mera ghar hai",
      "ye mera ghar hy",
    ],
    words: [
      {
        urdu: "یہ",
        roman_primary: "ye",
        roman_accepted_variants: ["ye", "yi", "yah", "yeh"],
        english_meaning: "this",
      },
      {
        urdu: "میرا",
        roman_primary: "mera",
        roman_accepted_variants: ["mera", "maira", "myra"],
        english_meaning: "my",
      },
      {
        urdu: "گھر",
        roman_primary: "ghar",
        roman_accepted_variants: ["ghar", "gahr", "gher"],
        english_meaning: "home",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s016",
    urdu: "وہ کھانا کھا رہا ہے",
    roman_primary: "woh khana kha raha hai",
    roman_accepted_variants: [
      "woh khana kha raha hai",
      "wo khana kha raha hai",
      "vo khana kha raha hai",
      "woh khana kha raha hy",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/that",
      },
      {
        urdu: "کھانا",
        roman_primary: "khana",
        roman_accepted_variants: ["khana", "khaana"],
        english_meaning: "food/to eat",
        components: [
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ھ", name: "he", roman: "he", role: "aspirator" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
          { urdu: "ن", name: "noon", roman: "noon", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "کھا",
        roman_primary: "kha",
        roman_accepted_variants: ["kha", "khaa"],
        english_meaning: "eat",
        components: [
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ھ", name: "he", roman: "he", role: "aspirator" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "رہا",
        roman_primary: "raha",
        roman_accepted_variants: ["raha", "reha", "rahaa"],
        english_meaning: "staying (masculine)",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s017",
    urdu: "وہ پانی پی رہا ہے",
    roman_primary: "woh paani pee raha hai",
    roman_accepted_variants: [
      "woh paani pee raha hai",
      "wo pani pi raha hai",
      "vo paani pi raha hai",
      "woh pani pee raha hy",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/that",
      },
      {
        urdu: "پانی",
        roman_primary: "paani",
        roman_accepted_variants: ["paani", "pani"],
        english_meaning: "water",
      },
      {
        urdu: "پی",
        roman_primary: "pee",
        roman_accepted_variants: ["pee", "pi", "pe"],
        english_meaning: "drink",
        components: [
          { urdu: "پ", name: "pe", roman: "pe", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
        ],
      },
      {
        urdu: "رہا",
        roman_primary: "raha",
        roman_accepted_variants: ["raha", "reha", "rahaa"],
        english_meaning: "staying (masculine)",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s018",
    urdu: "وہ کتاب پڑھ رہا ہے",
    roman_primary: "woh kitab parh raha hai",
    roman_accepted_variants: [
      "woh kitab parh raha hai",
      "wo kitaab parh raha hai",
      "vo kitab parh raha hai",
      "woh kitab par raha hai",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/that",
      },
      {
        urdu: "کتاب",
        roman_primary: "kitab",
        roman_accepted_variants: ["kitab", "kitaab", "ketaab", "ketab"],
        english_meaning: "book",
      },
      {
        urdu: "پڑھ",
        roman_primary: "parh",
        roman_accepted_variants: ["parh", "par", "parrh"],
        english_meaning: "read",
        components: [
          { urdu: "پ", name: "pe", roman: "pe", role: "consonant" },
          { urdu: "ڑ", name: "rre", roman: "rre", role: "consonant" },
          { urdu: "ھ", name: "he", roman: "he", role: "aspirator" },
        ],
      },
      {
        urdu: "رہا",
        roman_primary: "raha",
        roman_accepted_variants: ["raha", "reha", "rahaa"],
        english_meaning: "staying (masculine)",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s019",
    urdu: "وہ سکول جا رہی ہے",
    roman_primary: "woh school ja rahi hai",
    roman_accepted_variants: [
      "woh school ja rahi hai",
      "wo school ja rahi hai",
      "vo school ja rahi hai",
      "woh iskul ja rahi hai",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "she/that",
      },
      {
        urdu: "سکول",
        roman_primary: "school",
        roman_accepted_variants: ["school", "iskul", "skool"],
        english_meaning: "school",
        components: [
          { urdu: "س", name: "seen", roman: "seen", role: "consonant" },
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "و", name: "wao", roman: "wao", role: "vowel" },
          { urdu: "ل", name: "lam", roman: "lam", role: "consonant" },
        ],
      },
      {
        urdu: "جا",
        roman_primary: "ja",
        roman_accepted_variants: ["ja", "jaa", "jha"],
        english_meaning: "go",
      },
      {
        urdu: "رہی",
        roman_primary: "rahi",
        roman_accepted_variants: ["rahi", "rehi", "rahii"],
        english_meaning: "staying (feminine)",
        components: [
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s020",
    urdu: "وہ بازار جا رہا ہے",
    roman_primary: "woh bazaar ja raha hai",
    roman_accepted_variants: [
      "woh bazaar ja raha hai",
      "wo bazar ja raha hai",
      "vo bazaar ja raha hai",
      "woh bazaar jaa raha hai",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/that",
      },
      {
        urdu: "بازار",
        roman_primary: "bazaar",
        roman_accepted_variants: ["bazaar", "bazar", "baza"],
        english_meaning: "market",
        components: [
          { urdu: "ب", name: "be", roman: "be", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
          { urdu: "ز", name: "ze", roman: "ze", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
        ],
      },
      {
        urdu: "جا",
        roman_primary: "ja",
        roman_accepted_variants: ["ja", "jaa", "jha"],
        english_meaning: "go",
      },
      {
        urdu: "رہا",
        roman_primary: "raha",
        roman_accepted_variants: ["raha", "reha", "rahaa"],
        english_meaning: "staying (masculine)",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s021",
    urdu: "وہ بہت اچھا ہے",
    roman_primary: "woh bahut achha hai",
    roman_accepted_variants: [
      "woh bahut achha hai",
      "wo bahut acha hai",
      "vo bahut achha hai",
      "woh bohat achha hai",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/that",
      },
      {
        urdu: "بہت",
        roman_primary: "bahut",
        roman_accepted_variants: ["bahut", "bohat", "bohot"],
        english_meaning: "very/much",
        components: [
          { urdu: "ب", name: "be", roman: "be", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "consonant" },
          { urdu: "ت", name: "te", roman: "te", role: "consonant" },
        ],
      },
      {
        urdu: "اچھا",
        roman_primary: "achha",
        roman_accepted_variants: ["acha", "achha", "accha"],
        english_meaning: "good",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s022",
    urdu: "یہ بہت اچھی کتاب ہے",
    roman_primary: "ye bahut achhi kitab hai",
    roman_accepted_variants: [
      "ye bahut achhi kitab hai",
      "ye bohat achi kitab hai",
      "yi bahut achhi kitaab hai",
    ],
    words: [
      {
        urdu: "یہ",
        roman_primary: "ye",
        roman_accepted_variants: ["ye", "yi", "yah", "yeh"],
        english_meaning: "this",
      },
      {
        urdu: "بہت",
        roman_primary: "bahut",
        roman_accepted_variants: ["bahut", "bohat", "bohot"],
        english_meaning: "very",
      },
      {
        urdu: "اچھی",
        roman_primary: "achhi",
        roman_accepted_variants: ["achi", "achhi", "acchi"],
        english_meaning: "good (feminine)",
      },
      {
        urdu: "کتاب",
        roman_primary: "kitab",
        roman_accepted_variants: ["kitab", "kitaab", "ketaab", "ketab"],
        english_meaning: "book",
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s023",
    urdu: "وہ کہاں رہتا ہے",
    roman_primary: "woh kahan rehta hai",
    roman_accepted_variants: [
      "woh kahan rehta hai",
      "wo kahan rehta hai",
      "vo kahan rahta hai",
      "woh kahan rehta hy",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/that",
      },
      {
        urdu: "کہاں",
        roman_primary: "kahan",
        roman_accepted_variants: ["kahan", "kahan"],
        english_meaning: "where",
      },
      {
        urdu: "رہتا",
        roman_primary: "rehta",
        roman_accepted_variants: ["rehta", "rahta", "rehta"],
        english_meaning: "lives (masculine)",
        components: [
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "consonant" },
          { urdu: "ت", name: "te", roman: "te", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s024",
    urdu: "وہ کہاں رہتی ہے",
    roman_primary: "woh kahan rehti hai",
    roman_accepted_variants: [
      "woh kahan rehti hai",
      "wo kahan rehti hai",
      "vo kahan rahti hai",
      "woh kahan rehti hy",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "she/that",
      },
      {
        urdu: "کہاں",
        roman_primary: "kahan",
        roman_accepted_variants: ["kahan", "kahan"],
        english_meaning: "where",
      },
      {
        urdu: "رہتی",
        roman_primary: "rehti",
        roman_accepted_variants: ["rehti", "rahti", "rehti"],
        english_meaning: "lives (feminine)",
        components: [
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "consonant" },
          { urdu: "ت", name: "te", roman: "te", role: "consonant" },
          { urdu: "ی", name: "ye", roman: "ye", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "beginner",
  },
  {
    id: "s025",
    urdu: "وہ روزانہ ورزش کرتا ہے",
    roman_primary: "woh rozana warzish karta hai",
    roman_accepted_variants: [
      "woh rozana warzish karta hai",
      "wo rozana warzish karta hai",
      "vo rozana warzish karta hai",
      "woh rozana varzish karta hai",
    ],
    words: [
      {
        urdu: "وہ",
        roman_primary: "woh",
        roman_accepted_variants: ["woh", "wo", "vo", "voh"],
        english_meaning: "he/that",
      },
      {
        urdu: "روزانہ",
        roman_primary: "rozana",
        roman_accepted_variants: ["rozana", "rozanah", "roznah"],
        english_meaning: "daily",
        components: [
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
          { urdu: "و", name: "wao", roman: "wao", role: "vowel" },
          { urdu: "ز", name: "ze", roman: "ze", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
          { urdu: "ن", name: "noon", roman: "noon", role: "consonant" },
          { urdu: "ہ", name: "he", roman: "he", role: "vowel" },
        ],
      },
      {
        urdu: "ورزش",
        roman_primary: "warzish",
        roman_accepted_variants: ["warzish", "varzish", "warjish"],
        english_meaning: "exercise",
        components: [
          { urdu: "و", name: "wao", roman: "wao", role: "consonant" },
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
          { urdu: "ز", name: "ze", roman: "ze", role: "consonant" },
          { urdu: "ش", name: "sheen", roman: "sheen", role: "consonant" },
        ],
      },
      {
        urdu: "کرتا",
        roman_primary: "karta",
        roman_accepted_variants: ["karta", "karta", "kartha"],
        english_meaning: "does (masculine)",
        components: [
          { urdu: "ک", name: "kaf", roman: "kaf", role: "consonant" },
          { urdu: "ر", name: "re", roman: "re", role: "consonant" },
          { urdu: "ت", name: "te", roman: "te", role: "consonant" },
          { urdu: "ا", name: "alef", roman: "alif", role: "vowel" },
        ],
      },
      {
        urdu: "ہے",
        roman_primary: "hai",
        roman_accepted_variants: ["hai", "hy", "hain"],
        english_meaning: "is",
      },
    ],
    difficulty: "easy",
  },
];
