export type UrduWord = {
  roman: string;
  urdu_script: string;
  meaning: string;
};

export const UrduWordBank: UrduWord[] = [
  // ─── 1. Emotions & Feelings ───────────────────────────────────────────
  { roman: "mohabbat", urdu_script: "محبت", meaning: "love" },
  { roman: "gham", urdu_script: "غم", meaning: "sorrow" },
  { roman: "khushi", urdu_script: "خوشی", meaning: "happiness" },
  { roman: "dard", urdu_script: "درد", meaning: "pain" },
  { roman: "gussa", urdu_script: "غصہ", meaning: "anger" },
  { roman: "umeed", urdu_script: "امید", meaning: "hope" },
  { roman: "sukoon", urdu_script: "سکون", meaning: "peace" },
  { roman: "ishq", urdu_script: "عشق", meaning: "passionate love" },
  { roman: "aansoo", urdu_script: "آنسو", meaning: "tears" },
  { roman: "yaad", urdu_script: "یاد", meaning: "remembrance" },
  { roman: "shukr", urdu_script: "شکر", meaning: "gratitude" },
  { roman: "armaan", urdu_script: "ارمان", meaning: "longing" },
  { roman: "tamanna", urdu_script: "تمنا", meaning: "wish" },
  { roman: "aarzoo", urdu_script: "آرزو", meaning: "aspiration" },
  { roman: "wehshat", urdu_script: "وحشت", meaning: "dread" },
  { roman: "nafrat", urdu_script: "نفرت", meaning: "hatred" },
  { roman: "wafa", urdu_script: "وفا", meaning: "loyalty" },
  { roman: "bewafa", urdu_script: "بے وفا", meaning: "disloyal" },
  { roman: "fikr", urdu_script: "فکر", meaning: "worry" },
  { roman: "shak", urdu_script: "شک", meaning: "doubt" },
  { roman: "yaqeen", urdu_script: "یقین", meaning: "certainty" },
  { roman: "jazba", urdu_script: "جذبہ", meaning: "emotion" },
  { roman: "josh", urdu_script: "جوش", meaning: "enthusiasm" },
  { roman: "bechain", urdu_script: "بے چین", meaning: "restless" },
  { roman: "udaas", urdu_script: "اداس", meaning: "sad" },
  { roman: "masroor", urdu_script: "مسرور", meaning: "joyful" },
  { roman: "ranj", urdu_script: "رنج", meaning: "grief" },
  { roman: "afsos", urdu_script: "افسوس", meaning: "regret" },
  { roman: "hairat", urdu_script: "حیرت", meaning: "wonder" },
  { roman: "taajjub", urdu_script: "تعجب", meaning: "surprise" },
  { roman: "himmat", urdu_script: "ہمت", meaning: "courage" },
  { roman: "rahat", urdu_script: "راحت", meaning: "comfort" },
  { roman: "nemat", urdu_script: "نعمت", meaning: "blessing" },
  { roman: "aah", urdu_script: "آہ", meaning: "sigh" },
  { roman: "wada", urdu_script: "وعدہ", meaning: "promise" },
  { roman: "qasam", urdu_script: "قسم", meaning: "oath" },
  { roman: "hansi", urdu_script: "ہنسی", meaning: "laughter" },
  { roman: "sapna", urdu_script: "سپنا", meaning: "dream" },
  { roman: "bhool", urdu_script: "بھول", meaning: "forgetting" },
  { roman: "akela", urdu_script: "اکیلا", meaning: "alone" },
  { roman: "tanha", urdu_script: "تنہا", meaning: "lonely" },
  { roman: "beqarar", urdu_script: "بے قرار", meaning: "restless/anxious" },
  { roman: "shaad", urdu_script: "شاد", meaning: "happy" },
  { roman: "dilgir", urdu_script: "دلگیر", meaning: "heartbroken" },
  { roman: "shikwa", urdu_script: "شکوہ", meaning: "complaint" },
  { roman: "khafa", urdu_script: "خفا", meaning: "annoyed" },
  { roman: "jazbaat", urdu_script: "جذبات", meaning: "emotions" },
  { roman: "taklif", urdu_script: "تکلیف", meaning: "trouble" },
  { roman: "pareshaan", urdu_script: "پریشان", meaning: "worried" },
  { roman: "chahat", urdu_script: "چاہت", meaning: "desire" },
  { roman: "lagan", urdu_script: "لگن", meaning: "dedication" },
  { roman: "kasak", urdu_script: "کسک", meaning: "pang" },
  { roman: "betaab", urdu_script: "بے تاب", meaning: "impatient" },
  { roman: "wahem", urdu_script: "وہم", meaning: "delusion" },
  { roman: "hasad", urdu_script: "حسد", meaning: "envy" },
  { roman: "kina", urdu_script: "کینہ", meaning: "malice" },
  { roman: "rahm", urdu_script: "رحم", meaning: "mercy" },
  { roman: "shafqat", urdu_script: "شفقت", meaning: "affection" },
  { roman: "naaz", urdu_script: "ناز", meaning: "coquetry" },
  { roman: "itminan", urdu_script: "اطمینان", meaning: "satisfaction" },
  { roman: "azab", urdu_script: "عذاب", meaning: "torment" },
  { roman: "khwaish", urdu_script: "خواہش", meaning: "desire" },
  { roman: "murad", urdu_script: "مراد", meaning: "purpose" },
  { roman: "gila", urdu_script: "گلہ", meaning: "grievance" },
  { roman: "lutf", urdu_script: "لطف", meaning: "pleasure" },
  { roman: "mazaa", urdu_script: "مزہ", meaning: "fun" },
  { roman: "pyar", urdu_script: "پیار", meaning: "affection" },
  { roman: "fakhr", urdu_script: "فخر", meaning: "pride" },
  { roman: "zillat", urdu_script: "ذلت", meaning: "humiliation" },
  { roman: "izzat", urdu_script: "عزت", meaning: "honour" },
  { roman: "ehsas", urdu_script: "احساس", meaning: "feeling" },
  { roman: "karaar", urdu_script: "قرار", meaning: "stability" },
  { roman: "muskaan", urdu_script: "مسکان", meaning: "smile" },
  { roman: "tabassum", urdu_script: "تبسم", meaning: "smile (poetic)" },
  { roman: "haya", urdu_script: "حیا", meaning: "modesty" },
  { roman: "sharm", urdu_script: "شرم", meaning: "shame" },
  { roman: "khauf", urdu_script: "خوف", meaning: "fear" },
  { roman: "darr", urdu_script: "ڈر", meaning: "fright" },
  { roman: "diler", urdu_script: "دلیر", meaning: "brave" },
  { roman: "buzdil", urdu_script: "بزدل", meaning: "cowardly" },
  { roman: "junoon", urdu_script: "جنون", meaning: "passion/madness" },
  { roman: "diwana", urdu_script: "دیوانہ", meaning: "lovesick" },
  { roman: "masst", urdu_script: "مست", meaning: "carefree" },
  { roman: "bedard", urdu_script: "بے درد", meaning: "heartless" },
  { roman: "meherbaan", urdu_script: "مہربان", meaning: "kind" },
  { roman: "ziddi", urdu_script: "ضدی", meaning: "stubborn" },
  { roman: "bura", urdu_script: "برا", meaning: "bad" },
  { roman: "achha", urdu_script: "اچھا", meaning: "good" },
  { roman: "pyara", urdu_script: "پیارا", meaning: "dear/beloved" },
  { roman: "mahboob", urdu_script: "محبوب", meaning: "beloved" },
  { roman: "tanhaai", urdu_script: "تنہائی", meaning: "solitude" },
  { roman: "bewafaai", urdu_script: "بے وفائی", meaning: "betrayal" },
  { roman: "shikayat", urdu_script: "شکایت", meaning: "complaint" },
  { roman: "khuloos", urdu_script: "خلوص", meaning: "sincerity" },
  { roman: "ghairat", urdu_script: "غیرت", meaning: "self-respect" },
  { roman: "sabr", urdu_script: "صبر", meaning: "patience" },
  { roman: "qismat", urdu_script: "قسمت", meaning: "fate" },
  { roman: "naseeb", urdu_script: "نصیب", meaning: "destiny" },
  { roman: "zindagi", urdu_script: "زندگی", meaning: "life" },

  // ─── 2. Nature & Environment ──────────────────────────────────────────
  { roman: "darya", urdu_script: "دریا", meaning: "river" },
  { roman: "pahar", urdu_script: "پہاڑ", meaning: "mountain" },
  { roman: "asman", urdu_script: "آسمان", meaning: "sky" },
  { roman: "zameen", urdu_script: "زمین", meaning: "earth" },
  { roman: "aag", urdu_script: "آگ", meaning: "fire" },
  { roman: "pani", urdu_script: "پانی", meaning: "water" },
  { roman: "hawa", urdu_script: "ہوا", meaning: "wind/air" },
  { roman: "mitti", urdu_script: "مٹی", meaning: "soil/dust" },
  { roman: "roshni", urdu_script: "روشنی", meaning: "light" },
  { roman: "andhera", urdu_script: "اندھیرا", meaning: "darkness" },
  { roman: "chand", urdu_script: "چاند", meaning: "moon" },
  { roman: "taara", urdu_script: "تارہ", meaning: "star" },
  { roman: "suraj", urdu_script: "سورج", meaning: "sun" },
  { roman: "baarish", urdu_script: "بارش", meaning: "rain" },
  { roman: "barf", urdu_script: "برف", meaning: "snow" },
  { roman: "toofaan", urdu_script: "طوفان", meaning: "storm" },
  { roman: "bijli", urdu_script: "بجلی", meaning: "lightning" },
  { roman: "badal", urdu_script: "بادل", meaning: "cloud" },
  { roman: "nadi", urdu_script: "ندی", meaning: "stream" },
  { roman: "samandar", urdu_script: "سمندر", meaning: "ocean" },
  { roman: "jangal", urdu_script: "جنگل", meaning: "forest" },
  { roman: "phool", urdu_script: "پھول", meaning: "flower" },
  { roman: "patta", urdu_script: "پتہ", meaning: "leaf" },
  { roman: "darakht", urdu_script: "درخت", meaning: "tree" },
  { roman: "ghaas", urdu_script: "گھاس", meaning: "grass" },
  { roman: "khet", urdu_script: "کھیت", meaning: "field/farm" },
  { roman: "maidaan", urdu_script: "میدان", meaning: "plain/ground" },
  { roman: "bahaar", urdu_script: "بہار", meaning: "spring season" },
  { roman: "sahil", urdu_script: "ساحل", meaning: "shore/coast" },
  { roman: "jharna", urdu_script: "جھرنا", meaning: "waterfall" },
  { roman: "jheel", urdu_script: "جھیل", meaning: "lake" },
  { roman: "chashma", urdu_script: "چشمہ", meaning: "spring/fountain" },
  { roman: "khazaan", urdu_script: "خزاں", meaning: "autumn" },
  { roman: "garmi", urdu_script: "گرمی", meaning: "heat/summer" },
  { roman: "sardi", urdu_script: "سردی", meaning: "cold/winter" },
  { roman: "mausam", urdu_script: "موسم", meaning: "season/weather" },
  { roman: "dhoop", urdu_script: "دھوپ", meaning: "sunshine" },
  { roman: "chaanv", urdu_script: "چھاؤں", meaning: "shade" },
  { roman: "aandhi", urdu_script: "آندھی", meaning: "dust storm" },
  { roman: "seli", urdu_script: "سیلاب", meaning: "flood" },
  { roman: "kuhraah", urdu_script: "کہرا", meaning: "fog/mist" },
  { roman: "sitara", urdu_script: "ستارہ", meaning: "star" },
  { roman: "maah", urdu_script: "ماہ", meaning: "moon (poetic)" },
  { roman: "aftaab", urdu_script: "آفتاب", meaning: "sun (poetic)" },
  { roman: "khalaa", urdu_script: "خلا", meaning: "space/emptiness" },
  { roman: "dhool", urdu_script: "دھول", meaning: "dust" },
  { roman: "dhuaan", urdu_script: "دھواں", meaning: "smoke" },
  { roman: "surkh", urdu_script: "سرخ", meaning: "red" },
  { roman: "sabz", urdu_script: "سبز", meaning: "green" },
  { roman: "safed", urdu_script: "سفید", meaning: "white" },
  { roman: "kaala", urdu_script: "کالا", meaning: "black" },
  { roman: "zard", urdu_script: "زرد", meaning: "yellow" },
  { roman: "gulabi", urdu_script: "گلابی", meaning: "pink" },
  { roman: "chamak", urdu_script: "چمک", meaning: "shine/glitter" },
  { roman: "lahren", urdu_script: "لہریں", meaning: "waves" },
  { roman: "ret", urdu_script: "ریت", meaning: "sand" },
  { roman: "pathhar", urdu_script: "پتھر", meaning: "stone" },
  { roman: "panchi", urdu_script: "پنچھی", meaning: "bird" },
  { roman: "titli", urdu_script: "تتلی", meaning: "butterfly" },
  { roman: "machli", urdu_script: "مچھلی", meaning: "fish" },
  { roman: "sher", urdu_script: "شیر", meaning: "lion" },
  { roman: "hiran", urdu_script: "ہرن", meaning: "deer" },
  { roman: "kirna", urdu_script: "کرن", meaning: "ray of light" },
  { roman: "ghata", urdu_script: "گھٹا", meaning: "dark clouds" },
  { roman: "fizaa", urdu_script: "فضا", meaning: "atmosphere" },
  { roman: "wadi", urdu_script: "وادی", meaning: "valley" },
  { roman: "dasht", urdu_script: "دشت", meaning: "wilderness" },
  { roman: "sahara", urdu_script: "صحرا", meaning: "desert" },
  { roman: "chaman", urdu_script: "چمن", meaning: "meadow/garden" },
  { roman: "gulshan", urdu_script: "گلشن", meaning: "rose garden" },
  { roman: "roshan", urdu_script: "روشن", meaning: "bright" },
  { roman: "taareek", urdu_script: "تاریک", meaning: "dark" },
  { roman: "gehra", urdu_script: "گہرا", meaning: "deep" },
  { roman: "ooncha", urdu_script: "اونچا", meaning: "high/tall" },
  { roman: "sookha", urdu_script: "سوکھا", meaning: "dry" },
  { roman: "taza", urdu_script: "تازہ", meaning: "fresh" },
  { roman: "narm", urdu_script: "نرم", meaning: "soft" },
  { roman: "garam", urdu_script: "گرم", meaning: "hot" },
  { roman: "thanda", urdu_script: "ٹھنڈا", meaning: "cold" },
  { roman: "sunsaan", urdu_script: "سنسان", meaning: "desolate" },
  { roman: "kohsar", urdu_script: "کوہسار", meaning: "mountain range" },
  { roman: "biyaabaan", urdu_script: "بیابان", meaning: "wilderness" },
  { roman: "daman", urdu_script: "دامن", meaning: "foot of a mountain" },
  { roman: "noor", urdu_script: "نور", meaning: "light/radiance" },
  { roman: "sarsarahat", urdu_script: "سرسراہٹ", meaning: "rustling" },
  { roman: "lehraana", urdu_script: "لہرانا", meaning: "to flutter/wave" },
  { roman: "khilna", urdu_script: "کھلنا", meaning: "to bloom" },
  { roman: "chaandi", urdu_script: "چاندی", meaning: "silver" },
  { roman: "sona", urdu_script: "سونا", meaning: "gold" },
  { roman: "parinda", urdu_script: "پرندہ", meaning: "bird" },
  { roman: "baagh", urdu_script: "باغ", meaning: "garden/tiger" },
  { roman: "shabnam", urdu_script: "شبنم", meaning: "dew" },
  { roman: "awaz", urdu_script: "آواز", meaning: "sound/voice" },
  { roman: "narangi", urdu_script: "نارنگی", meaning: "orange (color)" },
  { roman: "asmani", urdu_script: "آسمانی", meaning: "sky blue" },
  { roman: "komal", urdu_script: "کومل", meaning: "tender/soft" },

  // ─── 3. Relationships & People ────────────────────────────────────────
  { roman: "maa", urdu_script: "ماں", meaning: "mother" },
  { roman: "baap", urdu_script: "باپ", meaning: "father" },
  { roman: "bhai", urdu_script: "بھائی", meaning: "brother" },
  { roman: "behen", urdu_script: "بہن", meaning: "sister" },
  { roman: "dost", urdu_script: "دوست", meaning: "friend" },
  { roman: "beta", urdu_script: "بیٹا", meaning: "son" },
  { roman: "beti", urdu_script: "بیٹی", meaning: "daughter" },
  { roman: "dada", urdu_script: "دادا", meaning: "paternal grandfather" },
  { roman: "dadi", urdu_script: "دادی", meaning: "paternal grandmother" },
  { roman: "nana", urdu_script: "نانا", meaning: "maternal grandfather" },
  { roman: "nani", urdu_script: "نانی", meaning: "maternal grandmother" },
  { roman: "chacha", urdu_script: "چچا", meaning: "paternal uncle" },
  { roman: "chachi", urdu_script: "چچی", meaning: "paternal aunt (uncle's wife)" },
  { roman: "khala", urdu_script: "خالہ", meaning: "maternal aunt" },
  { roman: "mama", urdu_script: "ماما", meaning: "maternal uncle" },
  { roman: "phuphi", urdu_script: "پھوپھی", meaning: "paternal aunt" },
  { roman: "shauhar", urdu_script: "شوہر", meaning: "husband" },
  { roman: "biwi", urdu_script: "بیوی", meaning: "wife" },
  { roman: "bachcha", urdu_script: "بچہ", meaning: "child" },
  { roman: "padosi", urdu_script: "پڑوسی", meaning: "neighbour" },
  { roman: "mehman", urdu_script: "مہمان", meaning: "guest" },
  { roman: "yaar", urdu_script: "یار", meaning: "friend/buddy" },
  { roman: "saathi", urdu_script: "ساتھی", meaning: "companion" },
  { roman: "hamsafar", urdu_script: "ہمسفر", meaning: "travel companion" },
  { roman: "rishtedaar", urdu_script: "رشتہ دار", meaning: "relative" },
  { roman: "buzurg", urdu_script: "بزرگ", meaning: "elder" },
  { roman: "jawaan", urdu_script: "جوان", meaning: "young" },
  { roman: "ladka", urdu_script: "لڑکا", meaning: "boy" },
  { roman: "ladki", urdu_script: "لڑکی", meaning: "girl" },
  { roman: "mard", urdu_script: "مرد", meaning: "man" },
  { roman: "aurat", urdu_script: "عورت", meaning: "woman" },
  { roman: "dushman", urdu_script: "دشمن", meaning: "enemy" },
  { roman: "mezdaan", urdu_script: "میزبان", meaning: "host" },
  { roman: "rafiiq", urdu_script: "رفیق", meaning: "companion" },
  { roman: "hamsaya", urdu_script: "ہمسایہ", meaning: "neighbour" },
  { roman: "fakeer", urdu_script: "فقیر", meaning: "dervish/poor man" },
  { roman: "ameer", urdu_script: "امیر", meaning: "rich/prince" },
  { roman: "garib", urdu_script: "غریب", meaning: "poor" },
  { roman: "raja", urdu_script: "راجہ", meaning: "king" },
  { roman: "shahzada", urdu_script: "شہزادہ", meaning: "prince" },
  { roman: "shahzadi", urdu_script: "شہزادی", meaning: "princess" },
  { roman: "qaum", urdu_script: "قوم", meaning: "nation" },
  { roman: "ummat", urdu_script: "امت", meaning: "community" },
  { roman: "khaandaan", urdu_script: "خاندان", meaning: "family/clan" },
  { roman: "nasl", urdu_script: "نسل", meaning: "generation" },
  { roman: "judaa", urdu_script: "جدا", meaning: "separated" },
  { roman: "begaana", urdu_script: "بیگانہ", meaning: "stranger" },
  { roman: "pardesi", urdu_script: "پردیسی", meaning: "foreigner" },
  { roman: "musafir", urdu_script: "مسافر", meaning: "traveller" },
  { roman: "wafadaar", urdu_script: "وفادار", meaning: "faithful" },
  { roman: "aashiq", urdu_script: "عاشق", meaning: "lover" },
  { roman: "maashooqa", urdu_script: "معشوقہ", meaning: "beloved (f)" },
  { roman: "shohrat", urdu_script: "شہرت", meaning: "fame" },
  { roman: "abba", urdu_script: "ابا", meaning: "father (informal)" },
  { roman: "amma", urdu_script: "اماں", meaning: "mother (informal)" },
  { roman: "sahib", urdu_script: "صاحب", meaning: "sir/gentleman" },
  { roman: "begum", urdu_script: "بیگم", meaning: "lady/wife" },
  { roman: "ustaad", urdu_script: "استاد", meaning: "teacher/master" },
  { roman: "shagird", urdu_script: "شاگرد", meaning: "student/disciple" },
  { roman: "pir", urdu_script: "پیر", meaning: "spiritual guide" },
  { roman: "mureed", urdu_script: "مرید", meaning: "disciple" },
  { roman: "hakim", urdu_script: "حکیم", meaning: "wise man/doctor" },
  { roman: "qazi", urdu_script: "قاضی", meaning: "judge" },
  { roman: "sipahi", urdu_script: "سپاہی", meaning: "soldier" },
  { roman: "sardar", urdu_script: "سردار", meaning: "leader/chief" },
  { roman: "badshah", urdu_script: "بادشاہ", meaning: "king/emperor" },
  { roman: "darwesh", urdu_script: "درویش", meaning: "wandering mystic" },
  { roman: "tajir", urdu_script: "تاجر", meaning: "merchant" },
  { roman: "kisaan", urdu_script: "کسان", meaning: "farmer" },
  { roman: "mazdoor", urdu_script: "مزدور", meaning: "labourer" },
  { roman: "ahl", urdu_script: "اہل", meaning: "family/people" },
  { roman: "watan", urdu_script: "وطن", meaning: "homeland" },
  { roman: "insaan", urdu_script: "انسان", meaning: "human being" },
  { roman: "baba", urdu_script: "بابا", meaning: "father/old man" },
  { roman: "bachpan", urdu_script: "بچپن", meaning: "childhood" },
  { roman: "budhapa", urdu_script: "بڑھاپا", meaning: "old age" },
  { roman: "jawani", urdu_script: "جوانی", meaning: "youth" },
  { roman: "imandaar", urdu_script: "ایماندار", meaning: "honest" },
  { roman: "jhootha", urdu_script: "جھوٹا", meaning: "liar" },
  { roman: "yaari", urdu_script: "یاری", meaning: "friendship" },
  { roman: "milap", urdu_script: "ملاپ", meaning: "reunion/meeting" },
  { roman: "bichchhadna", urdu_script: "بچھڑنا", meaning: "to part/separate" },
  { roman: "sacha", urdu_script: "سچا", meaning: "true/honest" },
  { roman: "rishtah", urdu_script: "رشتہ", meaning: "relationship/bond" },
  { roman: "mahbooba", urdu_script: "محبوبہ", meaning: "beloved (f)" },
  { roman: "vazeer", urdu_script: "وزیر", meaning: "minister" },
  { roman: "safeer", urdu_script: "سفیر", meaning: "ambassador" },
  { roman: "rani", urdu_script: "رانی", meaning: "queen" },

  // ─── 4. Time & Numbers ────────────────────────────────────────────────
  { roman: "kal", urdu_script: "کل", meaning: "yesterday/tomorrow" },
  { roman: "aaj", urdu_script: "آج", meaning: "today" },
  { roman: "subah", urdu_script: "صبح", meaning: "morning" },
  { roman: "raat", urdu_script: "رات", meaning: "night" },
  { roman: "saal", urdu_script: "سال", meaning: "year" },
  { roman: "waqt", urdu_script: "وقت", meaning: "time" },
  { roman: "lamha", urdu_script: "لمحہ", meaning: "moment" },
  { roman: "ek", urdu_script: "ایک", meaning: "one" },
  { roman: "do", urdu_script: "دو", meaning: "two" },
  { roman: "teen", urdu_script: "تین", meaning: "three" },
  { roman: "char", urdu_script: "چار", meaning: "four" },
  { roman: "panch", urdu_script: "پانچ", meaning: "five" },
  { roman: "chhe", urdu_script: "چھ", meaning: "six" },
  { roman: "saat", urdu_script: "سات", meaning: "seven" },
  { roman: "aath", urdu_script: "آٹھ", meaning: "eight" },
  { roman: "nau", urdu_script: "نو", meaning: "nine" },
  { roman: "das", urdu_script: "دس", meaning: "ten" },
  { roman: "bees", urdu_script: "بیس", meaning: "twenty" },
  { roman: "pachaas", urdu_script: "پچاس", meaning: "fifty" },
  { roman: "sau", urdu_script: "سو", meaning: "hundred" },
  { roman: "hazar", urdu_script: "ہزار", meaning: "thousand" },
  { roman: "lakh", urdu_script: "لاکھ", meaning: "hundred thousand" },
  { roman: "maazi", urdu_script: "ماضی", meaning: "past" },
  { roman: "mustaqbil", urdu_script: "مستقبل", meaning: "future" },
  { roman: "haal", urdu_script: "حال", meaning: "present/condition" },
  { roman: "din", urdu_script: "دن", meaning: "day" },
  { roman: "hafta", urdu_script: "ہفتہ", meaning: "week" },
  { roman: "maheena", urdu_script: "مہینہ", meaning: "month" },
  { roman: "sadi", urdu_script: "صدی", meaning: "century" },
  { roman: "dopahar", urdu_script: "دوپہر", meaning: "afternoon" },
  { roman: "sham", urdu_script: "شام", meaning: "evening" },
  { roman: "sawera", urdu_script: "سویرا", meaning: "dawn" },
  { roman: "pehla", urdu_script: "پہلا", meaning: "first" },
  { roman: "aakhri", urdu_script: "آخری", meaning: "last" },
  { roman: "purana", urdu_script: "پرانا", meaning: "old" },
  { roman: "naya", urdu_script: "نیا", meaning: "new" },
  { roman: "qadiim", urdu_script: "قدیم", meaning: "ancient" },
  { roman: "jadeed", urdu_script: "جدید", meaning: "modern" },
  { roman: "jaldi", urdu_script: "جلدی", meaning: "hurry/quickly" },
  { roman: "aahista", urdu_script: "آہستہ", meaning: "slowly" },
  { roman: "abhi", urdu_script: "ابھی", meaning: "right now" },
  { roman: "hamesha", urdu_script: "ہمیشہ", meaning: "always" },
  { roman: "kabhi", urdu_script: "کبھی", meaning: "sometimes/ever" },
  { roman: "aksar", urdu_script: "اکثر", meaning: "often" },
  { roman: "ziyada", urdu_script: "زیادہ", meaning: "more/much" },
  { roman: "kam", urdu_script: "کم", meaning: "less/few" },
  { roman: "bahut", urdu_script: "بہت", meaning: "very/much" },
  { roman: "thoda", urdu_script: "تھوڑا", meaning: "a little" },
  { roman: "poora", urdu_script: "پورا", meaning: "complete/full" },
  { roman: "aadha", urdu_script: "آدھا", meaning: "half" },
  { roman: "baar", urdu_script: "بار", meaning: "time/occasion" },
  { roman: "roz", urdu_script: "روز", meaning: "daily" },
  { roman: "der", urdu_script: "دیر", meaning: "delay/late" },
  { roman: "pehle", urdu_script: "پہلے", meaning: "before" },
  { roman: "baad", urdu_script: "بعد", meaning: "after" },
  { roman: "beech", urdu_script: "بیچ", meaning: "middle" },
  { roman: "zaroor", urdu_script: "ضرور", meaning: "definitely" },
  { roman: "shayad", urdu_script: "شاید", meaning: "perhaps" },
  { roman: "agar", urdu_script: "اگر", meaning: "if" },
  { roman: "lekin", urdu_script: "لیکن", meaning: "but" },
  { roman: "phir", urdu_script: "پھر", meaning: "then/again" },
  { roman: "aur", urdu_script: "اور", meaning: "and/more" },
  { roman: "nahi", urdu_script: "نہیں", meaning: "no/not" },
  { roman: "haan", urdu_script: "ہاں", meaning: "yes" },
  { roman: "bilkul", urdu_script: "بالکل", meaning: "absolutely" },
  { roman: "matlab", urdu_script: "مطلب", meaning: "meaning/purpose" },
  { roman: "ghanta", urdu_script: "گھنٹہ", meaning: "hour" },
  { roman: "muddat", urdu_script: "مدت", meaning: "period/duration" },
  { roman: "umer", urdu_script: "عمر", meaning: "age/lifetime" },
  { roman: "taareekh", urdu_script: "تاریخ", meaning: "date/history" },
  { roman: "nazdeek", urdu_script: "نزدیک", meaning: "near/close" },
  { roman: "faasilah", urdu_script: "فاصلہ", meaning: "distance" },
  { roman: "samay", urdu_script: "سمے", meaning: "time/era" },
  { roman: "zamana", urdu_script: "زمانہ", meaning: "era/age" },
  { roman: "daur", urdu_script: "دور", meaning: "era/period" },
  { roman: "kab", urdu_script: "کب", meaning: "when" },
  { roman: "kitna", urdu_script: "کتنا", meaning: "how much" },
  { roman: "sirf", urdu_script: "صرف", meaning: "only" },
  { roman: "warna", urdu_script: "ورنہ", meaning: "otherwise" },
  { roman: "tabhi", urdu_script: "تبھی", meaning: "only then" },
  { roman: "doosra", urdu_script: "دوسرا", meaning: "second/other" },
  { roman: "teesra", urdu_script: "تیسرا", meaning: "third" },
  { roman: "kuch", urdu_script: "کچھ", meaning: "something/some" },

  // ─── 5. Body & Health ─────────────────────────────────────────────────
  { roman: "dil", urdu_script: "دل", meaning: "heart" },
  { roman: "ankh", urdu_script: "آنکھ", meaning: "eye" },
  { roman: "haath", urdu_script: "ہاتھ", meaning: "hand" },
  { roman: "sehat", urdu_script: "صحت", meaning: "health" },
  { roman: "sar", urdu_script: "سر", meaning: "head" },
  { roman: "zaban", urdu_script: "زبان", meaning: "tongue/language" },
  { roman: "pair", urdu_script: "پیر", meaning: "foot/leg" },
  { roman: "jism", urdu_script: "جسم", meaning: "body" },
  { roman: "khoon", urdu_script: "خون", meaning: "blood" },
  { roman: "bimari", urdu_script: "بیماری", meaning: "illness" },
  { roman: "dawaa", urdu_script: "دوا", meaning: "medicine" },
  { roman: "naak", urdu_script: "ناک", meaning: "nose" },
  { roman: "kaan", urdu_script: "کان", meaning: "ear" },
  { roman: "dant", urdu_script: "دانت", meaning: "teeth" },
  { roman: "muh", urdu_script: "منہ", meaning: "mouth/face" },
  { roman: "baal", urdu_script: "بال", meaning: "hair" },
  { roman: "gardan", urdu_script: "گردن", meaning: "neck" },
  { roman: "peeth", urdu_script: "پیٹھ", meaning: "back" },
  { roman: "pet", urdu_script: "پیٹ", meaning: "stomach" },
  { roman: "seena", urdu_script: "سینہ", meaning: "chest" },
  { roman: "kaandha", urdu_script: "کاندھا", meaning: "shoulder" },
  { roman: "ghutna", urdu_script: "گھٹنا", meaning: "knee" },
  { roman: "paon", urdu_script: "پاؤں", meaning: "feet" },
  { roman: "ungli", urdu_script: "انگلی", meaning: "finger" },
  { roman: "angutha", urdu_script: "انگوٹھا", meaning: "thumb" },
  { roman: "hatheli", urdu_script: "ہتھیلی", meaning: "palm" },
  { roman: "maatha", urdu_script: "ماتھا", meaning: "forehead" },
  { roman: "gaal", urdu_script: "گال", meaning: "cheek" },
  { roman: "hont", urdu_script: "ہونٹ", meaning: "lips" },
  { roman: "daadhi", urdu_script: "داڑھی", meaning: "beard" },
  { roman: "saans", urdu_script: "سانس", meaning: "breath" },
  { roman: "dhadkan", urdu_script: "دھڑکن", meaning: "heartbeat" },
  { roman: "nabz", urdu_script: "نبض", meaning: "pulse" },
  { roman: "haddi", urdu_script: "ہڈی", meaning: "bone" },
  { roman: "chamdi", urdu_script: "چمڑی", meaning: "skin" },
  { roman: "zakhm", urdu_script: "زخم", meaning: "wound" },
  { roman: "ilaj", urdu_script: "علاج", meaning: "treatment/cure" },
  { roman: "marham", urdu_script: "مرہم", meaning: "ointment/balm" },
  { roman: "neend", urdu_script: "نیند", meaning: "sleep" },
  { roman: "bhookh", urdu_script: "بھوک", meaning: "hunger" },
  { roman: "pyaas", urdu_script: "پیاس", meaning: "thirst" },
  { roman: "thakaan", urdu_script: "تھکاوٹ", meaning: "fatigue" },
  { roman: "kamzori", urdu_script: "کمزوری", meaning: "weakness" },
  { roman: "taaqat", urdu_script: "طاقت", meaning: "power/strength" },
  { roman: "kamzor", urdu_script: "کمزور", meaning: "weak" },
  { roman: "mazboot", urdu_script: "مضبوط", meaning: "strong" },
  { roman: "mota", urdu_script: "موٹا", meaning: "fat" },
  { roman: "patla", urdu_script: "پتلا", meaning: "thin" },
  { roman: "lamba", urdu_script: "لمبا", meaning: "tall/long" },
  { roman: "bukhaar", urdu_script: "بخار", meaning: "fever" },
  { roman: "khansi", urdu_script: "کھانسی", meaning: "cough" },
  { roman: "zukaam", urdu_script: "زکام", meaning: "cold/flu" },
  { roman: "chakar", urdu_script: "چکر", meaning: "dizziness" },
  { roman: "ulti", urdu_script: "الٹی", meaning: "nausea/vomit" },
  { roman: "marz", urdu_script: "مرض", meaning: "disease" },
  { roman: "tabiyat", urdu_script: "طبیعت", meaning: "health/temperament" },
  { roman: "aafiyat", urdu_script: "عافیت", meaning: "wellbeing" },
  { roman: "parhez", urdu_script: "پرہیز", meaning: "diet restriction" },
  { roman: "ghiza", urdu_script: "غذا", meaning: "nourishment" },
  { roman: "jigar", urdu_script: "جگر", meaning: "liver/courage" },
  { roman: "dimagh", urdu_script: "دماغ", meaning: "brain/mind" },
  { roman: "aqal", urdu_script: "عقل", meaning: "intelligence" },
  { roman: "hosh", urdu_script: "ہوش", meaning: "consciousness" },
  { roman: "kohni", urdu_script: "کہنی", meaning: "elbow" },
  { roman: "ankein", urdu_script: "آنکھیں", meaning: "eyes" },
  { roman: "palak", urdu_script: "پلک", meaning: "eyelid" },
  { roman: "aibru", urdu_script: "ابرو", meaning: "eyebrow" },
  { roman: "moochh", urdu_script: "مونچھ", meaning: "moustache" },
  { roman: "nashaa", urdu_script: "نشہ", meaning: "intoxication" },
  { roman: "azlaa", urdu_script: "عضلہ", meaning: "muscle" },
  { roman: "nafs", urdu_script: "نفس", meaning: "self/soul" },
  { roman: "rooh", urdu_script: "روح", meaning: "soul/spirit" },
  { roman: "qalb", urdu_script: "قلب", meaning: "heart (spiritual)" },
  { roman: "zor", urdu_script: "زور", meaning: "force/strength" },
  { roman: "tezi", urdu_script: "تیزی", meaning: "speed/sharpness" },
  { roman: "shahrag", urdu_script: "شہرگ", meaning: "jugular vein" },
  { roman: "sukh", urdu_script: "سکھ", meaning: "wellbeing/comfort" },
  { roman: "hifazat", urdu_script: "حفاظت", meaning: "protection" },
  { roman: "chota", urdu_script: "چھوٹا", meaning: "small/short" },
  { roman: "bada", urdu_script: "بڑا", meaning: "big/tall" },
  { roman: "taang", urdu_script: "ٹانگ", meaning: "leg" },

  // ─── 6. Food & Drink ──────────────────────────────────────────────────
  { roman: "roti", urdu_script: "روٹی", meaning: "flatbread" },
  { roman: "chai", urdu_script: "چائے", meaning: "tea" },
  { roman: "doodh", urdu_script: "دودھ", meaning: "milk" },
  { roman: "gosht", urdu_script: "گوشت", meaning: "meat" },
  { roman: "chawal", urdu_script: "چاول", meaning: "rice" },
  { roman: "daal", urdu_script: "دال", meaning: "lentils" },
  { roman: "namak", urdu_script: "نمک", meaning: "salt" },
  { roman: "cheeni", urdu_script: "چینی", meaning: "sugar" },
  { roman: "ghee", urdu_script: "گھی", meaning: "clarified butter" },
  { roman: "anda", urdu_script: "انڈا", meaning: "egg" },
  { roman: "sabzi", urdu_script: "سبزی", meaning: "vegetables" },
  { roman: "mirch", urdu_script: "مرچ", meaning: "chilli/pepper" },
  { roman: "meva", urdu_script: "میوہ", meaning: "fruit/dry fruit" },
  { roman: "sharbat", urdu_script: "شربت", meaning: "sweet drink" },
  { roman: "halwa", urdu_script: "حلوہ", meaning: "sweet pudding" },
  { roman: "lassi", urdu_script: "لسی", meaning: "yogurt drink" },
  { roman: "shorba", urdu_script: "شوربہ", meaning: "broth/soup" },
  { roman: "biryani", urdu_script: "بریانی", meaning: "biryani" },
  { roman: "kebab", urdu_script: "کباب", meaning: "kebab" },
  { roman: "paratha", urdu_script: "پراٹھا", meaning: "fried flatbread" },
  { roman: "naan", urdu_script: "نان", meaning: "naan bread" },
  { roman: "kheer", urdu_script: "کھیر", meaning: "rice pudding" },
  { roman: "mithaai", urdu_script: "مٹھائی", meaning: "sweets" },
  { roman: "ladoo", urdu_script: "لڈو", meaning: "sweet ball" },
  { roman: "barfi", urdu_script: "برفی", meaning: "milk sweet" },
  { roman: "achaar", urdu_script: "اچار", meaning: "pickle" },
  { roman: "chutney", urdu_script: "چٹنی", meaning: "chutney/sauce" },
  { roman: "masala", urdu_script: "مسالہ", meaning: "spices" },
  { roman: "zeera", urdu_script: "زیرہ", meaning: "cumin" },
  { roman: "haldi", urdu_script: "ہلدی", meaning: "turmeric" },
  { roman: "adrak", urdu_script: "ادرک", meaning: "ginger" },
  { roman: "lehsun", urdu_script: "لہسن", meaning: "garlic" },
  { roman: "pyaaz", urdu_script: "پیاز", meaning: "onion" },
  { roman: "tamatar", urdu_script: "ٹماٹر", meaning: "tomato" },
  { roman: "aloo", urdu_script: "آلو", meaning: "potato" },
  { roman: "murghi", urdu_script: "مرغی", meaning: "chicken" },
  { roman: "jhinga", urdu_script: "جھینگا", meaning: "prawn/shrimp" },
  { roman: "baigan", urdu_script: "بینگن", meaning: "eggplant" },
  { roman: "gobi", urdu_script: "گوبھی", meaning: "cauliflower" },
  { roman: "saag", urdu_script: "ساگ", meaning: "leafy greens" },
  { roman: "karela", urdu_script: "کریلا", meaning: "bitter gourd" },
  { roman: "matar", urdu_script: "مٹر", meaning: "peas" },
  { roman: "gehoon", urdu_script: "گندم", meaning: "wheat" },
  { roman: "moong", urdu_script: "مونگ", meaning: "green lentils" },
  { roman: "chana", urdu_script: "چنا", meaning: "chickpea" },
  { roman: "akhrot", urdu_script: "اخروٹ", meaning: "walnut" },
  { roman: "badam", urdu_script: "بادام", meaning: "almond" },
  { roman: "pista", urdu_script: "پستہ", meaning: "pistachio" },
  { roman: "khajoor", urdu_script: "کھجور", meaning: "date fruit" },
  { roman: "angoor", urdu_script: "انگور", meaning: "grapes" },
  { roman: "kela", urdu_script: "کیلا", meaning: "banana" },
  { roman: "seb", urdu_script: "سیب", meaning: "apple" },
  { roman: "aam", urdu_script: "آم", meaning: "mango" },
  { roman: "amrood", urdu_script: "امرود", meaning: "guava" },
  { roman: "anar", urdu_script: "انار", meaning: "pomegranate" },
  { roman: "tarbooz", urdu_script: "تربوز", meaning: "watermelon" },
  { roman: "nimbu", urdu_script: "لیموں", meaning: "lemon" },
  { roman: "qehwa", urdu_script: "قہوہ", meaning: "herbal/green tea" },
  { roman: "aab", urdu_script: "آب", meaning: "water (poetic)" },
  { roman: "shahad", urdu_script: "شہد", meaning: "honey" },
  { roman: "makkhan", urdu_script: "مکھن", meaning: "butter" },
  { roman: "paneer", urdu_script: "پنیر", meaning: "cottage cheese" },
  { roman: "dahi", urdu_script: "دہی", meaning: "yogurt/curd" },
  { roman: "malai", urdu_script: "ملائی", meaning: "cream" },
  { roman: "kaddoo", urdu_script: "کدو", meaning: "pumpkin" },
  { roman: "bhindi", urdu_script: "بھنڈی", meaning: "okra" },
  { roman: "gajar", urdu_script: "گاجر", meaning: "carrot" },
  { roman: "mooli", urdu_script: "مولی", meaning: "radish" },
  { roman: "makka", urdu_script: "مکا", meaning: "corn/maize" },
  { roman: "saunf", urdu_script: "سونف", meaning: "fennel/anise" },
  { roman: "elaichi", urdu_script: "الائچی", meaning: "cardamom" },
  { roman: "darchini", urdu_script: "دار چینی", meaning: "cinnamon" },
  { roman: "sirka", urdu_script: "سرکہ", meaning: "vinegar" },
  { roman: "nashpati", urdu_script: "ناشپاتی", meaning: "pear" },
  { roman: "paalak", urdu_script: "پالک", meaning: "spinach" },
  { roman: "rajma", urdu_script: "راجمہ", meaning: "kidney beans" },
  { roman: "paan", urdu_script: "پان", meaning: "betel leaf" },
  { roman: "kaju", urdu_script: "کاجو", meaning: "cashew" },
  { roman: "kharboza", urdu_script: "خربوزہ", meaning: "melon" },
  { roman: "tori", urdu_script: "توری", meaning: "ridge gourd" },
  { roman: "arvi", urdu_script: "اروی", meaning: "taro root" },

  // ─── 7. Places & Travel ───────────────────────────────────────────────
  { roman: "ghar", urdu_script: "گھر", meaning: "home" },
  { roman: "sheher", urdu_script: "شہر", meaning: "city" },
  { roman: "gaon", urdu_script: "گاؤں", meaning: "village" },
  { roman: "raasta", urdu_script: "راستہ", meaning: "road/path" },
  { roman: "bazaar", urdu_script: "بازار", meaning: "market" },
  { roman: "masjid", urdu_script: "مسجد", meaning: "mosque" },
  { roman: "dukan", urdu_script: "دکان", meaning: "shop" },
  { roman: "darwaza", urdu_script: "دروازہ", meaning: "door/gate" },
  { roman: "safar", urdu_script: "سفر", meaning: "journey" },
  { roman: "mulk", urdu_script: "ملک", meaning: "country" },
  { roman: "mohalla", urdu_script: "محلہ", meaning: "neighbourhood" },
  { roman: "makan", urdu_script: "مکان", meaning: "house/building" },
  { roman: "manzil", urdu_script: "منزل", meaning: "destination" },
  { roman: "sarhad", urdu_script: "سرحد", meaning: "border" },
  { roman: "darbaar", urdu_script: "دربار", meaning: "royal court" },
  { roman: "imarat", urdu_script: "عمارت", meaning: "building" },
  { roman: "haspatal", urdu_script: "ہسپتال", meaning: "hospital" },
  { roman: "kitabkhana", urdu_script: "کتب خانہ", meaning: "library" },
  { roman: "bagh", urdu_script: "باغ", meaning: "garden" },
  { roman: "qabristan", urdu_script: "قبرستان", meaning: "graveyard" },
  { roman: "dargah", urdu_script: "درگاہ", meaning: "shrine" },
  { roman: "mandir", urdu_script: "مندر", meaning: "temple" },
  { roman: "jahaaz", urdu_script: "جہاز", meaning: "ship/aircraft" },
  { roman: "gaadi", urdu_script: "گاڑی", meaning: "vehicle/car" },
  { roman: "rail", urdu_script: "ریل", meaning: "train" },
  { roman: "tayyara", urdu_script: "طیارہ", meaning: "airplane" },
  { roman: "kishti", urdu_script: "کشتی", meaning: "boat" },
  { roman: "mahel", urdu_script: "محل", meaning: "palace" },
  { roman: "qila", urdu_script: "قلعہ", meaning: "fort/castle" },
  { roman: "deewar", urdu_script: "دیوار", meaning: "wall" },
  { roman: "khidki", urdu_script: "کھڑکی", meaning: "window" },
  { roman: "chhat", urdu_script: "چھت", meaning: "roof/ceiling" },
  { roman: "zina", urdu_script: "زینہ", meaning: "stairs" },
  { roman: "gali", urdu_script: "گلی", meaning: "alley/street" },
  { roman: "sarak", urdu_script: "سڑک", meaning: "road" },
  { roman: "pul", urdu_script: "پل", meaning: "bridge" },
  { roman: "chowk", urdu_script: "چوک", meaning: "town square" },
  { roman: "chauraha", urdu_script: "چوراہہ", meaning: "crossroads" },
  { roman: "station", urdu_script: "اسٹیشن", meaning: "station" },
  { roman: "bandargah", urdu_script: "بندرگاہ", meaning: "harbour" },
  { roman: "sarai", urdu_script: "سرائے", meaning: "inn/caravanserai" },
  { roman: "mazaar", urdu_script: "مزار", meaning: "shrine/mausoleum" },
  { roman: "khanqah", urdu_script: "خانقاہ", meaning: "Sufi lodge" },
  { roman: "talab", urdu_script: "تالاب", meaning: "pond" },
  { roman: "raah", urdu_script: "راہ", meaning: "path/way" },
  { roman: "simt", urdu_script: "سمت", meaning: "direction" },
  { roman: "taraf", urdu_script: "طرف", meaning: "direction/side" },
  { roman: "aagey", urdu_script: "آگے", meaning: "ahead/forward" },
  { roman: "peechhe", urdu_script: "پیچھے", meaning: "behind" },
  { roman: "daayein", urdu_script: "دائیں", meaning: "right direction" },
  { roman: "baayein", urdu_script: "بائیں", meaning: "left direction" },
  { roman: "seedha", urdu_script: "سیدھا", meaning: "straight" },
  { roman: "neeche", urdu_script: "نیچے", meaning: "below/down" },
  { roman: "oopar", urdu_script: "اوپر", meaning: "above/up" },
  { roman: "bahar", urdu_script: "باہر", meaning: "outside" },
  { roman: "andar", urdu_script: "اندر", meaning: "inside" },
  { roman: "samne", urdu_script: "سامنے", meaning: "in front of" },
  { roman: "wapas", urdu_script: "واپس", meaning: "back/return" },
  { roman: "pardais", urdu_script: "پردیس", meaning: "foreign land" },
  { roman: "qaafila", urdu_script: "قافلہ", meaning: "caravan" },
  { roman: "kocha", urdu_script: "کوچہ", meaning: "alley/lane" },
  { roman: "nehr", urdu_script: "نہر", meaning: "canal" },
  { roman: "baandh", urdu_script: "بندھ", meaning: "dam" },
  { roman: "maqaam", urdu_script: "مقام", meaning: "place/station" },
  { roman: "wapsi", urdu_script: "واپسی", meaning: "return journey" },
  { roman: "musafirkhana", urdu_script: "مسافرخانہ", meaning: "guesthouse" },
  { roman: "paas", urdu_script: "پاس", meaning: "nearby" },
  { roman: "dur", urdu_script: "دور", meaning: "far away" },
  { roman: "yahaan", urdu_script: "یہاں", meaning: "here" },
  { roman: "wahaan", urdu_script: "وہاں", meaning: "there" },
  { roman: "madrasah", urdu_script: "مدرسہ", meaning: "school/seminary" },
  { roman: "girja", urdu_script: "گرجا", meaning: "church" },
  { roman: "kaarkhana", urdu_script: "کارخانہ", meaning: "factory" },
  { roman: "imambara", urdu_script: "امام باڑہ", meaning: "Shia prayer hall" },
  { roman: "khaali", urdu_script: "خالی", meaning: "empty/vacant" },
  { roman: "khima", urdu_script: "خیمہ", meaning: "tent" },
  { roman: "naao", urdu_script: "ناؤ", meaning: "small boat" },

  // ─── 8. Actions & Verbs ───────────────────────────────────────────────
  { roman: "aana", urdu_script: "آنا", meaning: "to come" },
  { roman: "jaana", urdu_script: "جانا", meaning: "to go" },
  { roman: "khana", urdu_script: "کھانا", meaning: "to eat" },
  { roman: "peena", urdu_script: "پینا", meaning: "to drink" },
  { roman: "bolna", urdu_script: "بولنا", meaning: "to speak" },
  { roman: "sona", urdu_script: "سونا", meaning: "to sleep" },
  { roman: "uthna", urdu_script: "اٹھنا", meaning: "to rise/get up" },
  { roman: "baithna", urdu_script: "بیٹھنا", meaning: "to sit" },
  { roman: "parhna", urdu_script: "پڑھنا", meaning: "to read/study" },
  { roman: "likhna", urdu_script: "لکھنا", meaning: "to write" },
  { roman: "dekhna", urdu_script: "دیکھنا", meaning: "to see" },
  { roman: "sunna", urdu_script: "سننا", meaning: "to listen" },
  { roman: "chalna", urdu_script: "چلنا", meaning: "to walk" },
  { roman: "dena", urdu_script: "دینا", meaning: "to give" },
  { roman: "lena", urdu_script: "لینا", meaning: "to take" },
  { roman: "karna", urdu_script: "کرنا", meaning: "to do" },
  { roman: "hona", urdu_script: "ہونا", meaning: "to be" },
  { roman: "rehna", urdu_script: "رہنا", meaning: "to live/stay" },
  { roman: "chahna", urdu_script: "چاہنا", meaning: "to want/wish" },
  { roman: "sochna", urdu_script: "سوچنا", meaning: "to think" },
  { roman: "samajhna", urdu_script: "سمجھنا", meaning: "to understand" },
  { roman: "jaanna", urdu_script: "جاننا", meaning: "to know" },
  { roman: "bhoolna", urdu_script: "بھولنا", meaning: "to forget" },
  { roman: "hasna", urdu_script: "ہنسنا", meaning: "to laugh" },
  { roman: "rona", urdu_script: "رونا", meaning: "to cry" },
  { roman: "gaana", urdu_script: "گانا", meaning: "to sing" },
  { roman: "nachna", urdu_script: "ناچنا", meaning: "to dance" },
  { roman: "khailna", urdu_script: "کھیلنا", meaning: "to play" },
  { roman: "daudna", urdu_script: "دوڑنا", meaning: "to run" },
  { roman: "uchalna", urdu_script: "اچھلنا", meaning: "to jump" },
  { roman: "girna", urdu_script: "گرنا", meaning: "to fall" },
  { roman: "uthana", urdu_script: "اٹھانا", meaning: "to lift" },
  { roman: "rakhna", urdu_script: "رکھنا", meaning: "to keep/place" },
  { roman: "banana", urdu_script: "بنانا", meaning: "to make/create" },
  { roman: "todna", urdu_script: "توڑنا", meaning: "to break" },
  { roman: "khona", urdu_script: "کھونا", meaning: "to lose" },
  { roman: "pana", urdu_script: "پانا", meaning: "to find/get" },
  { roman: "batana", urdu_script: "بتانا", meaning: "to tell" },
  { roman: "poochna", urdu_script: "پوچھنا", meaning: "to ask" },
  { roman: "sunana", urdu_script: "سنانا", meaning: "to recite" },
  { roman: "sikhna", urdu_script: "سیکھنا", meaning: "to learn" },
  { roman: "sikhaana", urdu_script: "سکھانا", meaning: "to teach" },
  { roman: "bachana", urdu_script: "بچانا", meaning: "to save/protect" },
  { roman: "maarna", urdu_script: "مارنا", meaning: "to hit/beat" },
  { roman: "ladna", urdu_script: "لڑنا", meaning: "to fight" },
  { roman: "rokna", urdu_script: "روکنا", meaning: "to stop" },
  { roman: "chhodna", urdu_script: "چھوڑنا", meaning: "to leave/abandon" },
  { roman: "pakadna", urdu_script: "پکڑنا", meaning: "to catch/hold" },
  { roman: "kholna", urdu_script: "کھولنا", meaning: "to open" },
  { roman: "lautna", urdu_script: "لوٹنا", meaning: "to return" },
  { roman: "bhagna", urdu_script: "بھاگنا", meaning: "to flee" },
  { roman: "thakna", urdu_script: "تھکنا", meaning: "to get tired" },
  { roman: "jaagna", urdu_script: "جاگنا", meaning: "to be awake" },
  { roman: "badalana", urdu_script: "بدلنا", meaning: "to change" },
  { roman: "barhna", urdu_script: "بڑھنا", meaning: "to grow/increase" },
  { roman: "maangna", urdu_script: "مانگنا", meaning: "to ask for/beg" },
  { roman: "khinchna", urdu_script: "کھینچنا", meaning: "to pull/draw" },
  { roman: "chadhna", urdu_script: "چڑھنا", meaning: "to climb" },
  { roman: "utarna", urdu_script: "اترنا", meaning: "to descend" },
  { roman: "lagana", urdu_script: "لگانا", meaning: "to attach/apply" },
  { roman: "nikalna", urdu_script: "نکلنا", meaning: "to emerge/go out" },
  { roman: "ghusna", urdu_script: "گھسنا", meaning: "to enter" },
  { roman: "palatna", urdu_script: "پلٹنا", meaning: "to turn around" },
  { roman: "murhna", urdu_script: "مڑنا", meaning: "to turn/bend" },
  { roman: "pakana", urdu_script: "پکانا", meaning: "to cook" },
  { roman: "kharidna", urdu_script: "خریدنا", meaning: "to buy" },
  { roman: "bechna", urdu_script: "بیچنا", meaning: "to sell" },
  { roman: "dhoondna", urdu_script: "ڈھونڈنا", meaning: "to search" },
  { roman: "dhona", urdu_script: "دھونا", meaning: "to wash" },
  { roman: "khilaana", urdu_script: "کھلانا", meaning: "to feed" },
  { roman: "pilaana", urdu_script: "پلانا", meaning: "to give to drink" },
  { roman: "manaana", urdu_script: "منانا", meaning: "to celebrate/appease" },
  { roman: "rangna", urdu_script: "رنگنا", meaning: "to paint/colour" },
  { roman: "tairna", urdu_script: "تیرنا", meaning: "to swim" },
  { roman: "urna", urdu_script: "اڑنا", meaning: "to fly" },
  { roman: "ghoomna", urdu_script: "گھومنا", meaning: "to wander" },
  { roman: "talashna", urdu_script: "تلاشنا", meaning: "to search" },
  { roman: "padhana", urdu_script: "پڑھانا", meaning: "to teach" },
  { roman: "jorha", urdu_script: "جوڑنا", meaning: "to join/connect" },
  { roman: "chhupaana", urdu_script: "چھپانا", meaning: "to hide" },
  { roman: "milana", urdu_script: "ملانا", meaning: "to mix/connect" },
  { roman: "darrana", urdu_script: "ڈرانا", meaning: "to frighten" },
  { roman: "hansaana", urdu_script: "ہنسانا", meaning: "to make laugh" },

  // ─── 9. Poetry & Literature ───────────────────────────────────────────
  { roman: "shayar", urdu_script: "شاعر", meaning: "poet" },
  { roman: "ghazal", urdu_script: "غزل", meaning: "ghazal" },
  { roman: "nazm", urdu_script: "نظم", meaning: "poem" },
  { roman: "lafz", urdu_script: "لفظ", meaning: "word" },
  { roman: "sher", urdu_script: "شعر", meaning: "couplet" },
  { roman: "mushayra", urdu_script: "مشاعرہ", meaning: "poetry gathering" },
  { roman: "diwan", urdu_script: "دیوان", meaning: "collected poetry" },
  { roman: "kitaab", urdu_script: "کتاب", meaning: "book" },
  { roman: "kahani", urdu_script: "کہانی", meaning: "story" },
  { roman: "dastan", urdu_script: "داستان", meaning: "tale/legend" },
  { roman: "shairi", urdu_script: "شاعری", meaning: "poetry" },
  { roman: "adab", urdu_script: "ادب", meaning: "literature/respect" },
  { roman: "mazmoon", urdu_script: "مضمون", meaning: "essay/topic" },
  { roman: "afsana", urdu_script: "افسانہ", meaning: "short story" },
  { roman: "nasar", urdu_script: "نثر", meaning: "prose" },
  { roman: "qasida", urdu_script: "قصیدہ", meaning: "ode" },
  { roman: "rubai", urdu_script: "رباعی", meaning: "quatrain" },
  { roman: "marsiya", urdu_script: "مرثیہ", meaning: "elegy" },
  { roman: "rekhta", urdu_script: "ریختہ", meaning: "early Urdu poetry" },
  { roman: "masnavi", urdu_script: "مثنوی", meaning: "narrative poem" },
  { roman: "hamd", urdu_script: "حمد", meaning: "praise of God" },
  { roman: "naat", urdu_script: "نعت", meaning: "praise of Prophet" },
  { roman: "takhleeq", urdu_script: "تخلیق", meaning: "creation" },
  { roman: "takhayyal", urdu_script: "تخیل", meaning: "imagination" },
  { roman: "khyal", urdu_script: "خیال", meaning: "thought/imagination" },
  { roman: "tasawwur", urdu_script: "تصور", meaning: "conception/vision" },
  { roman: "ilham", urdu_script: "الہام", meaning: "inspiration" },
  { roman: "wazan", urdu_script: "وزن", meaning: "meter/weight" },
  { roman: "qafiya", urdu_script: "قافیہ", meaning: "rhyme" },
  { roman: "radif", urdu_script: "ردیف", meaning: "refrain in ghazal" },
  { roman: "maqta", urdu_script: "مقطع", meaning: "last couplet" },
  { roman: "matla", urdu_script: "مطلع", meaning: "opening couplet" },
  { roman: "beher", urdu_script: "بحر", meaning: "poetic meter" },
  { roman: "tashbih", urdu_script: "تشبیہ", meaning: "simile" },
  { roman: "istiara", urdu_script: "استعارہ", meaning: "metaphor" },
  { roman: "bayaan", urdu_script: "بیان", meaning: "expression/statement" },
  { roman: "balaaghat", urdu_script: "بلاغت", meaning: "rhetoric" },
  { roman: "tahrir", urdu_script: "تحریر", meaning: "writing/text" },
  { roman: "akhbaar", urdu_script: "اخبار", meaning: "newspaper" },
  { roman: "risaala", urdu_script: "رسالہ", meaning: "magazine/journal" },
  { roman: "riwayat", urdu_script: "روایت", meaning: "tradition/narration" },
  { roman: "hikayat", urdu_script: "حکایت", meaning: "tale/anecdote" },
  { roman: "kahavat", urdu_script: "کہاوت", meaning: "proverb" },
  { roman: "muhaavara", urdu_script: "محاورہ", meaning: "idiom" },
  { roman: "tehzeeb", urdu_script: "تہذیب", meaning: "civilization/culture" },
  { roman: "rasm", urdu_script: "رسم", meaning: "custom/tradition" },
  { roman: "wirasat", urdu_script: "وراثت", meaning: "heritage" },
  { roman: "naseem", urdu_script: "نسیم", meaning: "breeze" },
  { roman: "parvaaz", urdu_script: "پرواز", meaning: "flight/soaring" },
  { roman: "sur", urdu_script: "سُر", meaning: "musical note" },
  { roman: "taal", urdu_script: "تال", meaning: "rhythm/beat" },
  { roman: "naghma", urdu_script: "نغمہ", meaning: "melody/song" },
  { roman: "tarana", urdu_script: "ترانہ", meaning: "song/anthem" },
  { roman: "qawwali", urdu_script: "قوالی", meaning: "Sufi devotional music" },
  { roman: "lajawab", urdu_script: "لاجواب", meaning: "matchless" },
  { roman: "nadir", urdu_script: "نادر", meaning: "rare/unique" },
  { roman: "anmol", urdu_script: "انمول", meaning: "priceless" },
  { roman: "ajeeb", urdu_script: "عجیب", meaning: "strange/wonderful" },
  { roman: "kamaal", urdu_script: "کمال", meaning: "excellence" },
  { roman: "jamal", urdu_script: "جمال", meaning: "beauty" },
  { roman: "husn", urdu_script: "حسن", meaning: "beauty" },
  { roman: "fasahat", urdu_script: "فصاحت", meaning: "eloquence" },
  { roman: "zaheen", urdu_script: "ذہین", meaning: "intelligent" },
  { roman: "mutaalia", urdu_script: "مطالعہ", meaning: "study/reading" },
  { roman: "misaal", urdu_script: "مثال", meaning: "example" },
  { roman: "gulzar", urdu_script: "گلزار", meaning: "rose garden/poet name" },
  { roman: "saqafat", urdu_script: "ثقافت", meaning: "culture" },
  { roman: "rawaj", urdu_script: "رواج", meaning: "custom/practice" },
  { roman: "geet", urdu_script: "گیت", meaning: "song" },
  { roman: "naql", urdu_script: "نقل", meaning: "imitation/anecdote" },
  { roman: "raag", urdu_script: "راگ", meaning: "musical mode" },
  { roman: "andaz", urdu_script: "انداز", meaning: "style/manner" },
  { roman: "zeenat", urdu_script: "زینت", meaning: "adornment/beauty" },
  { roman: "parwana", urdu_script: "پروانہ", meaning: "moth/devotee" },
  { roman: "shamma", urdu_script: "شمع", meaning: "candle/flame" },
  { roman: "tajnis", urdu_script: "تجنیس", meaning: "wordplay/pun" },
  { roman: "ibaarat", urdu_script: "عبارت", meaning: "text/passage" },

  // ─── 10. Spirituality & Philosophy ───────────────────────────────────
  { roman: "khuda", urdu_script: "خدا", meaning: "God" },
  { roman: "ruh", urdu_script: "روح", meaning: "soul/spirit" },
  { roman: "iman", urdu_script: "ایمان", meaning: "faith" },
  { roman: "dua", urdu_script: "دعا", meaning: "prayer/supplication" },
  { roman: "noor", urdu_script: "نور", meaning: "divine light" },
  { roman: "banda", urdu_script: "بندہ", meaning: "servant/human being" },
  { roman: "jannat", urdu_script: "جنت", meaning: "paradise" },
  { roman: "dozakh", urdu_script: "دوزخ", meaning: "hell" },
  { roman: "tawba", urdu_script: "توبہ", meaning: "repentance" },
  { roman: "ibadat", urdu_script: "عبادت", meaning: "worship" },
  { roman: "fana", urdu_script: "فنا", meaning: "mortality/annihilation" },
  { roman: "haq", urdu_script: "حق", meaning: "truth/right" },
  { roman: "zikr", urdu_script: "ذکر", meaning: "remembrance of God" },
  { roman: "tawakkul", urdu_script: "توکل", meaning: "trust in God" },
  { roman: "hikmah", urdu_script: "حکمت", meaning: "wisdom" },
  { roman: "aakhirat", urdu_script: "آخرت", meaning: "afterlife" },
  { roman: "taqdeer", urdu_script: "تقدیر", meaning: "divine fate" },
  { roman: "qadar", urdu_script: "قدر", meaning: "divine decree/value" },
  { roman: "sifat", urdu_script: "صفت", meaning: "attribute/quality" },
  { roman: "zaat", urdu_script: "ذات", meaning: "essence/self" },
  { roman: "wujood", urdu_script: "وجود", meaning: "existence/being" },
  { roman: "adam", urdu_script: "عدم", meaning: "non-existence" },
  { roman: "baqaa", urdu_script: "بقا", meaning: "immortality" },
  { roman: "kashf", urdu_script: "کشف", meaning: "mystical revelation" },
  { roman: "miraaj", urdu_script: "معراج", meaning: "spiritual ascension" },
  { roman: "marqaba", urdu_script: "مراقبہ", meaning: "meditation" },
  { roman: "tasawwuf", urdu_script: "تصوف", meaning: "Sufism" },
  { roman: "sufi", urdu_script: "صوفی", meaning: "Sufi mystic" },
  { roman: "wali", urdu_script: "ولی", meaning: "saint/friend of God" },
  { roman: "murshid", urdu_script: "مرشد", meaning: "spiritual guide" },
  { roman: "sama", urdu_script: "سماع", meaning: "Sufi music/listening" },
  { roman: "wajd", urdu_script: "وجد", meaning: "spiritual ecstasy" },
  { roman: "wahdat", urdu_script: "وحدت", meaning: "unity/oneness" },
  { roman: "tauheed", urdu_script: "توحید", meaning: "oneness of God" },
  { roman: "nabuwwat", urdu_script: "نبوت", meaning: "prophethood" },
  { roman: "wahi", urdu_script: "وحی", meaning: "divine revelation" },
  { roman: "farz", urdu_script: "فرض", meaning: "obligation/duty" },
  { roman: "sadqa", urdu_script: "صدقہ", meaning: "charity" },
  { roman: "zakaat", urdu_script: "زکوٰۃ", meaning: "obligatory alms" },
  { roman: "hajj", urdu_script: "حج", meaning: "pilgrimage" },
  { roman: "namaz", urdu_script: "نماز", meaning: "prayer/salat" },
  { roman: "roza", urdu_script: "روزہ", meaning: "fast" },
  { roman: "tasbih", urdu_script: "تسبیح", meaning: "glorification/beads" },
  { roman: "azan", urdu_script: "اذان", meaning: "call to prayer" },
  { roman: "qibla", urdu_script: "قبلہ", meaning: "direction of prayer" },
  { roman: "mehrab", urdu_script: "محراب", meaning: "prayer niche" },
  { roman: "ghayb", urdu_script: "غیب", meaning: "unseen realm" },
  { roman: "jinn", urdu_script: "جن", meaning: "spirit/genie" },
  { roman: "batin", urdu_script: "باطن", meaning: "inner/esoteric" },
  { roman: "zaahir", urdu_script: "ظاہر", meaning: "outer/apparent" },
  { roman: "barkat", urdu_script: "برکت", meaning: "blessing/abundance" },
  { roman: "rehmat", urdu_script: "رحمت", meaning: "divine mercy" },
  { roman: "maghfirat", urdu_script: "مغفرت", meaning: "divine forgiveness" },
  { roman: "ghaflat", urdu_script: "غفلت", meaning: "heedlessness" },
  { roman: "islaah", urdu_script: "اصلاح", meaning: "reform/correction" },
  { roman: "mubarak", urdu_script: "مبارک", meaning: "blessed" },
  { roman: "taqdees", urdu_script: "تقدیس", meaning: "holiness" },
  { roman: "shirk", urdu_script: "شرک", meaning: "polytheism" },
  { roman: "shaheed", urdu_script: "شہید", meaning: "martyr" },
  { roman: "shahadat", urdu_script: "شہادت", meaning: "martyrdom" },
  { roman: "jihaad", urdu_script: "جہاد", meaning: "struggle/striving" },
  { roman: "malak", urdu_script: "ملک", meaning: "angel" },
  { roman: "sirr", urdu_script: "سر", meaning: "secret/mystery" },
  { roman: "karamaat", urdu_script: "کرامات", meaning: "miracles of saints" },
  { roman: "tawajjuh", urdu_script: "توجہ", meaning: "spiritual focus" },
  { roman: "ahwal", urdu_script: "احوال", meaning: "spiritual states" },
  { roman: "jazb", urdu_script: "جذب", meaning: "spiritual absorption" },
  { roman: "aql", urdu_script: "عقل", meaning: "intellect/reason" },
  { roman: "risaalat", urdu_script: "رسالت", meaning: "prophetic mission" },
  { roman: "sunnat", urdu_script: "سنت", meaning: "prophetic tradition" },
  { roman: "aadam", urdu_script: "آدم", meaning: "Adam/first human" },
  { roman: "aameen", urdu_script: "آمین", meaning: "amen" },
  { roman: "faiz", urdu_script: "فیض", meaning: "grace/benefit" },
  { roman: "sabr", urdu_script: "صبر", meaning: "patience/endurance" },
  { roman: "shukran", urdu_script: "شکران", meaning: "thankfulness" },
];
